clear all
use "C:/Users/Owner/OneDrive/Documents/Georgetown University/Thesis Writer/Research/QB Worth/Game Analysis/Data 7 Injuries.dta"

rename PLAYER Player
label variable Player Player
gen Index = _n
label variable Index "Index"

* Replace TeamID with team name
replace Team = "Atlanta Falcons"        if Team == "ATL"
replace Team = "Buffalo Bills"          if Team == "BUF"
replace Team = "Carolina Panthers"      if Team == "CAR"
replace Team = "Chicago Bears"          if Team == "CHI"
replace Team = "Cincinnati Bengals"     if Team == "CIN"
replace Team = "Cleveland Browns"       if Team == "CLE"
replace Team = "Indianapolis Colts"     if Team == "CLT"
replace Team = "Arizona Cardinals"      if Team == "CRD"
replace Team = "Dallas Cowboys"         if Team == "DAL"
replace Team = "Denver Broncos"         if Team == "DEN"
replace Team = "Detroit Lions"          if Team == "DET"
replace Team = "Green Bay Packers"      if Team == "GNB"
replace Team = "Houston Texans"         if Team == "HTX"
replace Team = "Jacksonville Jaguars"   if Team == "JAX"
replace Team = "Kansas City Chiefs"     if Team == "KAN"
replace Team = "Miami Dolphins"         if Team == "MIA"
replace Team = "Minnesota Vikings"      if Team == "MIN"
replace Team = "New Orleans Saints"     if Team == "NOR"
replace Team = "New England Patriots"   if Team == "NWE"
replace Team = "New York Giants"        if Team == "NYG"
replace Team = "New York Jets"          if Team == "NYJ"
replace Team = "Tennessee Titans"       if Team == "OTI"
replace Team = "Philadelphia Eagles"    if Team == "PHI"
replace Team = "Pittsburgh Steelers"    if Team == "PIT"
replace Team = "Las Vegas Raiders"      if Team == "RAI"
replace Team = "Los Angeles Rams"       if Team == "RAM"
replace Team = "Baltimore Ravens"       if Team == "RAV"
replace Team = "Los Angeles Chargers"   if Team == "SDG"
replace Team = "Seattle Seahawks"       if Team == "SEA"
replace Team = "San Francisco 49ers"    if Team == "SFO"
replace Team = "Tampa Bay Buccaneers"   if Team == "TAM"
replace Team = "Washington Commanders"  if Team == "WAS"
replace Season = Season + 2000
sort Team Season Player Index
order Index Player Team Season, first

*Distinguish between two different players with same name
replace Player = "Charles Johnson DE" if Player == "Charles Johnson" & Team == "Carolina Panthers" & Season == 2017 & Index == 1302
replace Player = "Charles Johnson WR" if Player == "Charles Johnson" & Team == "Carolina Panthers" & Season == 2017 & Index == 1303
replace Player = "Greg Jones RB" if Player == "Greg Jones" & Team == "Jacksonville Jaguars" & Season == 2012 & Index == 7877
replace Player = "Greg Jones MLB" if Player == "Greg Jones" & Team == "Jacksonville Jaguars" & Season == 2012 & Index == 7878
replace Player = "Jaylon Moore WR" if Player == "Jaylon Moore" & Team == "San Francisco 49ers" & Season == 2024 & Index == 17986
replace Player = "Jaylon Moore OL" if Player == "Jaylon Moore" & Team == "San Francisco 49ers" & Season == 2024 & Index == 17987

* Fix corrupted apostrophes
replace Player = subinstr(Player, "â€™", "'", .)

* Fix accented characters
replace Player = subinstr(Player, "Ã¡", "á", .)
replace Player = subinstr(Player, "Ã©", "é", .)
replace Player = subinstr(Player, "Ã¨", "è", .)
replace Player = subinstr(Player, "Ã­", "í", .)
replace Player = subinstr(Player, "Ã³", "ó", .)
replace Player = subinstr(Player, "Ãº", "ú", .)
replace Player = subinstr(Player, "Ã±", "ñ", .)
replace Player = subinstr(Player, "Ãœ", "Ü", .)
replace Player = subinstr(Player, "Ã‰", "É", .)
* replace Player = subinstr(Player, "Ã", "Á", .) // Often appears as standalone corruption

* Fix miscellaneous corruptions
replace Player = subinstr(Player, "Â", "", .)

* Match names to Money dataset (see "2 Game Corrections.xlsx")
gen OldPlayer = Player
replace Player = "Adrian Davis" if Player == "A.J. Davis"
replace Player = "A.J. Cole" if Player == "AJ Cole III"
replace Player = "A.J. Dillon" if Player == "AJ Dillon"
replace Player = "A.J. Finley" if Player == "AJ Finley"
replace Player = "A.J. Parker" if Player == "AJ Parker"
replace Player = "A.J. Terrell" if Player == "AJ Terrell"
replace Player = "Adam-Pacman Jones" if Player == "Adam Jones"
replace Player = "Alexander Green" if Player == "Alex Green"
replace Player = "Armani Taylor-Prioleau" if Player == "Alex Taylor-Prioleau"
replace Player = "A.J. Johnson" if Player == "Alexander Johnson"
replace Player = "Amaré Barno" if Player == "Amare Barno"
replace Player = "A.J. Uzodinma" if Player == "Amechi Uzodinma"
replace Player = "Andrew Adam" if Player == "Andrew Adams"
replace Player = "Andrew Booth Jr." if Player == "Andrew Booth"
replace Player = "Anthony McFarland" if Player == "Anthony McFarland Jr."
replace Player = "Anthony Walker Jr." if Player == "Anthony Walker"
replace Player = "Audric Estimé" if Player == "Audric Estime"
replace Player = "B.J. Johnson" if Player == "BJ Johnson"
replace Player = "B.J. Ojulari" if Player == "BJ Ojulari"
replace Player = "Benjamin Ijalana" if Player == "Ben Ijalana"
replace Player = "Benjamin Watson" if Player == "Ben Watson"
replace Player = "Carlos Basham Jr." if Player == "Boogie Basham"
replace Player = "Brenton Cox Jr." if Player == "Brenton Cox"
replace Player = "Brian Robinson" if Player == "Brian Robinson Jr."
replace Player = "Brian Thomas Jr." if Player == "Brian Thomas"
replace Player = "Briley Moore" if Player == "Briley Moore-McKinney"
replace Player = "Broderick Washington" if Player == "Broderick Washington Jr."
replace Player = "Olubunmi Rotimi" if Player == "Bunmi Rotimi"
replace Player = "Christian Bryant" if Player == "C.B. Bryant"
replace Player = "C.J. Akins" if Player == "C.J. Atkins"
replace Player = "Chauncey Gardner-Johnson" if Player == "C.J. Gardner-Johnson"
replace Player = "Carnell Williams" if Player == "Cadillac Williams"
replace Player = "Calvin Austin" if Player == "Calvin Austin III"
replace Player = "Cameron Brown" if Player == "Cam Brown"
replace Player = "Cam Lewis" if Player == "Cameron Lewis"
replace Player = "Cassanova Mckinzy" if Player == "Cassanova McKinzy"
replace Player = "Cedrick Wilson" if Player == "Cedrick Wilson Jr."
replace Player = "Charles Leno" if Player == "Charles Leno Jr."
replace Player = "Charlie Thomas III" if Player == "Charlie Thomas"
replace Player = "Chig Okonkwo" if Player == "Chigoziem Okonkwo"
replace Player = "Christopher Carson" if Player == "Chris Carson"
replace Player = "Christopher Conte" if Player == "Chris Conte"
replace Player = "Chris Harris" if Player == "Chris Harris Jr."
replace Player = "Christopher Owens" if Player == "Chris Owens"
replace Player = "Chris Rodriguez Jr." if Player == "Chris Rodriguez"
replace Player = "Chris Rumph II" if Player == "Chris Rumph"
replace Player = "Chris Campbell" if Player == "Christian Campbell"
replace Player = "Chris Milton" if Player == "Christopher Milton"
replace Player = "Clay Matthews Jr." if Player == "Clay Matthews"
replace Player = "Decobie Durant" if Player == "Cobie Durant"
replace Player = "Cory Trice Jr." if Player == "Cory Trice"
replace Player = "Crevon LeBlanc" if Player == "Cre'von LeBlanc"
replace Player = "D'ante Smith" if Player == "D'Ante Smith"
replace Player = "D'Cota Dixon" if Player == "D'cota Dixon"
replace Player = "Domonique Johnson" if Player == "D.J. Johnson"
replace Player = "DJ Montgomery" if Player == "D.J. Montgomery"
replace Player = "D.J. Ivey" if Player == "DJ Ivey"
replace Player = "D.J. Johnson" if Player == "DJ Johnson"
replace Player = "D.J. Turner" if Player == "DJ Turner"
replace Player = "Da'shawn Hand" if Player == "Da'Shawn Hand"
replace Player = "Davonte Lambert" if Player == "DaVonte Lambert"
replace Player = "Daesean Hamilton" if Player == "DaeSean Hamilton"
replace Player = "Damien Parms" if Player == "Damian Parms"
replace Player = "Dan Vitale" if Player == "Danny Vitale"
replace Player = "D.J. Ware" if Player == "Danny Ware"
replace Player = "Dante Fowler Jr." if Player == "Dante Fowler"
replace Player = "Darnell Savage" if Player == "Darnell Savage Jr."
replace Player = "Darrell Luter Jr." if Player == "Darrell Luter"
replace Player = "David White Jr." if Player == "David White"
replace Player = "DeVante Bausby" if Player == "De'Vante Bausby"
replace Player = "Devante Harris" if Player == "De'Vante Harris"
replace Player = "Devon Achane" if Player == "De'Von Achane"
replace Player = "Deandre Carter" if Player == "DeAndre Carter"
replace Player = "DeAndre Elliot" if Player == "DeAndre Elliott"
replace Player = "Deangelo Tyson" if Player == "DeAngelo Tyson"
replace Player = "Dee Alford" if Player == "DeAundre Alford"
replace Player = "Dejon Gomes" if Player == "DeJon Gomes"
replace Player = "Demarco Sampson" if Player == "DeMarco Sampson"
replace Player = "De'Quan Menzie" if Player == "DeQuan Menzie"
replace Player = "Deshawn Shead" if Player == "DeShawn Shead"
replace Player = "Deshon Elliott" if Player == "DeShon Elliott"
replace Player = "Deante' Gray" if Player == "Deante Gray"
replace Player = "Deatrich Wise" if Player == "Deatrich Wise Jr."
replace Player = "DeMarcus Love" if Player == "Demarcus Love"
replace Player = "Devin Bush" if Player == "Devin Bush Jr."
replace Player = "Dominique Williams" if Player == "Dom Williams"
replace Player = "Dominque Alexander" if Player == "Dominique Alexander"
replace Player = "Donavan Clark" if Player == "Donavon Clark"
replace Player = "Donte Stallworth" if Player == "Donte' Stallworth"
replace Player = "Dorance Armstrong" if Player == "Dorance Armstrong Jr."
replace Player = "Douglas Hogue" if Player == "Doug Hogue"
replace Player = "E.J. Manuel" if Player == "EJ Manuel"
replace Player = "Earnest Brown" if Player == "Earnest Brown IV"
replace Player = "Eddie Carmona" if Player == "Eddy Carmona"
replace Player = "Eddy Pineiro" if Player == "Eddy Piñeiro"
replace Player = "Evan Smith" if Player == "Evan Dietrich-Smith"
replace Player = "Fitz Toussaint" if Player == "Fitzgerald Toussaint"
replace Player = "Foley Fatukasi" if Player == "Folorunso Fatukasi"
replace Player = "Gardner Minshew" if Player == "Gardner Minshew II"
replace Player = "Garret Hartley" if Player == "Garrett Hartley"
replace Player = "Gary Jennings" if Player == "Gary Jennings Jr"
replace Player = "Geno Grissom" if Player == "Geneo Grissom"
replace Player = "George Asafo-adjei" if Player == "George Asafo-Adjei"
replace Player = "George Karlaftis" if Player == "George Karlaftis III"
replace Player = "Grant DuBose" if Player == "Grant Dubose"
replace Player = "Greg Newsome" if Player == "Greg Newsome II"
replace Player = "Greg Rousseau" if Player == "Gregory Rousseau"
replace Player = "Hamilcar Rashed" if Player == "Hamilcar Rashed Jr."
replace Player = "Hardy Nickerson Jr." if Player == "Hardy Nickerson"
replace Player = "Henry Ruggs" if Player == "Henry Ruggs III"
replace Player = "Ira Lewis" if Player == "Ira Savage-Lewis"
replace Player = "Irv Smith" if Player == "Irv Smith Jr."
replace Player = "Issac Redman" if Player == "Isaac Redman"
replace Player = "Isaac Taylor -Stuart" if Player == "Isaac Taylor-Stuart"
replace Player = "Jegs Jegede" if Player == "Iseoluwapo Jegede"
replace Player = "Ike Brown" if Player == "Isiah Brown"
replace Player = "JK Dobbins" if Player == "J.K. Dobbins"
replace Player = "J.J. Arcega-Whiteside" if Player == "JJ Arcega-Whiteside"
replace Player = "J.J. Nelson" if Player == "JJ Nelson"
replace Player = "J.P. Flynn" if Player == "JP Flynn"
replace Player = "J'Marcus Bradley" if Player == "Ja'Marcus Bradley"
replace Player = "Ja'whaun Bentley" if Player == "Ja'Whaun Bentley"
replace Player = "Janoris Jenkins" if Player == "Jackrabbit Jenkins"
replace Player = "Jake Martin" if Player == "Jacob Martin"
replace Player = "JaMycal Hasty" if Player == "Jamycal Hasty"
replace Player = "JaQuarius Landrews" if Player == "Jaquarius Landrews"
replace Player = "Jarvis Brownlee Jr." if Player == "Jarvis Brownlee"
replace Player = "Jason Taylor II" if Player == "Jason Taylor"
replace Player = "Javelin Guidry Jr." if Player == "Javelin Guidry"
replace Player = "Jayson Dimanche" if Player == "Jayson DiManche"
replace Player = "Jedrick Wills" if Player == "Jedrick Wills Jr."
replace Player = "Jeffrey Gunter" if Player == "Jeff Gunter"
replace Player = "Johnny Newton" if Player == "Jer'Zhan Newton"
replace Player = "Jermaine Carter" if Player == "Jermaine Carter Jr."
replace Player = "Jermaine Johnson" if Player == "Jermaine Johnson II"
replace Player = "Jermaine Kelly" if Player == "Jermaine Kelly Jr."
replace Player = "Jerrick Reed II" if Player == "Jerrick Reed"
replace Player = "JoLonn Dunbar" if Player == "Jo-Lonn Dunbar"
replace Player = "Jojo Domann" if Player == "JoJo Domann"
replace Player = "Joseph Anderson" if Player == "Joe Anderson"
replace Player = "Joseph Cheek" if Player == "Joe Cheek"
replace Player = "Joseph Morgan" if Player == "Joe Morgan"
replace Player = "Joe Tryon" if Player == "Joe Tryon-Shoyinka"
replace Player = "John Cyprien" if Player == "Johnathan Cyprien"
replace Player = "Jon Gaines II" if Player == "Jon Gaines"
replace Player = "Jon Runyan" if Player == "Jon Runyan Jr."
replace Player = "Jon Bostic" if Player == "Jonathan Bostic"
replace Player = "Johnathan Grimes" if Player == "Jonathan Grimes"
replace Player = "Joe Jones" if Player == "Joseph Jones"
replace Player = "Joshua Cribbs" if Player == "Josh Cribbs"
replace Player = "Joshua Hines-Allen" if Player == "Josh Hines-Allen"
replace Player = "Joshua Onujiogu" if Player == "Josh Onujiogu"
replace Player = "Joshua Thomas" if Player == "Josh Thomas"
replace Player = "Joshua Uche" if Player == "Josh Uche"
replace Player = "Josh Kelley" if Player == "Joshua Kelley"
replace Player = "Josh Simmons" if Player == "Joshua Simmons"
replace Player = "JuJu Hughes" if Player == "Juju Hughes"
replace Player = "Julie'n Davenport" if Player == "Julién Davenport"
replace Player = "K.C. McDermott" if Player == "KC McDermott"
replace Player = "K.J. Hamler" if Player == "KJ Hamler"
replace Player = "Kavontae Turpin" if Player == "KaVontae Turpin"
replace Player = "Keivarae Russell" if Player == "KeiVarae Russell"
replace Player = "Kenneth Walker" if Player == "Kenneth Walker III"
replace Player = "Khadarel Hodge" if Player == "KhaDarel Hodge"
replace Player = "Laron Byrd" if Player == "LaRon Byrd"
replace Player = "LaDarius Gunter" if Player == "Ladarius Gunter"
replace Player = "LaMarcus Joyner" if Player == "Lamarcus Joyner"
replace Player = "Delano Hill" if Player == "Lano Hill"
replace Player = "Laviska Shenault" if Player == "Laviska Shenault Jr."
replace Player = "LeRon McClain" if Player == "Le'Ron McClain"
replace Player = "Leroy Hill" if Player == "LeRoy Hill"
replace Player = "Levante Bellamy" if Player == "LeVante Bellamy"
replace Player = "Lil'jordan Humphrey" if Player == "Lil'Jordan Humphrey"
replace Player = "Lloyd Cushenberry" if Player == "Lloyd Cushenberry III"
replace Player = "Lonnie Johnson" if Player == "Lonnie Johnson Jr."
replace Player = "Louchiez Purifoy" if Player == "Loucheiz Purifoy"
replace Player = "Lynn Bowden" if Player == "Lynn Bowden Jr."
replace Player = "Maake Kemoeatu" if Player == "Ma'ake Kemoeatu"
replace Player = "Malcolm Rodríguez" if Player == "Malcolm Rodriguez"
replace Player = "Marshawn Lloyd" if Player == "MarShawn Lloyd"
replace Player = "Marion Barber" if Player == "Marion Barber III"
replace Player = "Mark Fields" if Player == "Mark Fields II"
replace Player = "Marvell Tell" if Player == "Marvell Tell III"
replace Player = "Matt Bosher" if Player == "Matthew Bosher"
replace Player = "Matt Dayes" if Player == "Matthew Dayes"
replace Player = "Matt Godin" if Player == "Matthew Godin"
replace Player = "Maurice Hurst" if Player == "Maurice Hurst Jr."
replace Player = "Mike Hoecht" if Player == "Michael Hoecht"
replace Player = "Mike Onwenu" if Player == "Michael Onwenu"
replace Player = "Mike Woods" if Player == "Michael Woods II"
replace Player = "Michael Ford" if Player == "Mike Ford"
replace Player = "Michael Liedtke" if Player == "Mike Liedtke"
replace Player = "Michael Morgan" if Player == "Mike Morgan"
replace Player = "Michael Neal" if Player == "Mike Neal"
replace Player = "Nail Diggs" if Player == "Na'il Diggs"
replace Player = "Navorro Bowman" if Player == "NaVorro Bowman"
replace Player = "Nate Gerry" if Player == "Nathan Gerry"
replace Player = "Chinedum Ndukwe" if Player == "Nedu Ndukwe"
replace Player = "Neil Farrell Jr." if Player == "Neil Farrell"
replace Player = "Nick Westbrook" if Player == "Nick Westbrook-Ikhine"
replace Player = "NIco Falah" if Player == "Nico Falah"
replace Player = "Nyheim Miller-Hines" if Player == "Nyheim Hines"
replace Player = "Oshiomogho Atogwe" if Player == "O.J. Atogwe"
replace Player = "Olu Fashanu" if Player == "Olumuyiwa Fashanu"
replace Player = "Phillip Walker" if Player == "P.J. Walker"
replace Player = "Patrick Angerer" if Player == "Pat Angerer"
replace Player = "Patrick Jones" if Player == "Patrick Jones II"
replace Player = "Phillip Loadholt" if Player == "Phil Loadholt"
replace Player = "Philip Steward" if Player == "Phillip Steward"
replace Player = "Jartavius Martin" if Player == "Quan Martin"
replace Player = "Reginald Diggs" if Player == "Reggie Diggs"
replace Player = "Reggie Robinson" if Player == "Reggie Robinson II"
replace Player = "Rezjohn Wright" if Player == "Rejzohn Wright"
replace Player = "Ricky Jean Francois" if Player == "Ricky Jean-Francois"
replace Player = "Rico Bussey Jr." if Player == "Rico Bussey"
replace Player = "Tariq Woolen" if Player == "Riq Woolen"
replace Player = "Robert Housler" if Player == "Rob Housler"
replace Player = "Robbie Anderson" if Player == "Robbie Chosen"
replace Player = "Robert Beal Jr." if Player == "Robert Beal"
replace Player = "Rob Kelley" if Player == "Robert Kelley"
replace Player = "Robert Tonyan Jr." if Player == "Robert Tonyan"
replace Player = "Rob Windsor" if Player == "Robert Windsor"
replace Player = "Rashad Carmichael" if Player == "Roc Carmichael"
replace Player = "Roderick Issac" if Player == "Rod Issac"
replace Player = "Rodney Thomas" if Player == "Rodney Thomas II"
replace Player = "Ron Leary" if Player == "Ronald Leary"
replace Player = "Johnathan Ford" if Player == "Rudy Ford"
replace Player = "Sam Eguavoen" if Player == "Samuel Eguavoen"
replace Player = "Ahmad Gardner" if Player == "Sauce Gardner"
replace Player = "Sav Rocca" if Player == "Saverio Rocca"
replace Player = "Scotty Miller" if Player == "Scott Miller"
replace Player = "Sean Bunting" if Player == "Sean Murphy-Bunting"
replace Player = "Sebastian Joseph" if Player == "Sebastian Joseph-Day"
replace Player = "Sederrick Cunningham" if Player == "Sederrik Cunningham"
replace Player = "Shaq Quarterman" if Player == "Shaquille Quarterman"
replace Player = "Shaun-Dion Hamilton" if Player == "Shaun Dion Hamilton"
replace Player = "Simmie Cobbs Jr." if Player == "Simmie Cobbs"
replace Player = "Stanley Morgan" if Player == "Stanley Morgan Jr."
replace Player = "Starling Thomas V" if Player == "Starling Thomas"
replace Player = "Steven Hauschka" if Player == "Stephen Hauschka"
replace Player = "Steve Schilling" if Player == "Stephen Schilling"
replace Player = "Steve Smith" if Player == "Steve Smith Sr."
replace Player = "Steven Sims Jr." if Player == "Steven Sims"
replace Player = "Iosua Opeta" if Player == "Sua Opeta"
replace Player = "Travis Carrie" if Player == "T.J. Carrie"
replace Player = "TJ Jones" if Player == "T.J. Jones"
replace Player = "Tevon Mutcherson" if Player == "T.J. Mutcherson"
replace Player = "TK McLendon Jr." if Player == "TK McLendon"
replace Player = "Cornellius Carradine" if Player == "Tank Carradine"
replace Player = "Jalen Tabor" if Player == "Teez Tabor"
replace Player = "Terrace Marshall" if Player == "Terrace Marshall Jr."
replace Player = "Bopete Keyes" if Player == "Thakarius Keyes"
replace Player = "Thayer Munford Jr." if Player == "Thayer Munford"
replace Player = "Thomas Graham Jr." if Player == "Thomas Graham"
replace Player = "Tre Hawkins III" if Player == "Tre Hawkins"
replace Player = "Tre'quan Smith" if Player == "Tre'Quan Smith"
replace Player = "Tre Tomlinson" if Player == "Tre'Vius Tomlinson"
replace Player = "Tre'Von Johnson" if Player == "Tre'von Johnson"
replace Player = "Trevon Moehrig" if Player == "Tre'von Moehrig"
replace Player = "Trenton Brown" if Player == "Trent Brown"
replace Player = "Trenton Robinson" if Player == "Trent Robinson"
replace Player = "TuTu Atwell" if Player == "Tutu Atwell"
replace Player = "Ty Davis-Price" if Player == "Tyrion Davis-Price"
replace Player = "Tyrone Tracy" if Player == "Tyrone Tracy Jr."
replace Player = "Velus Jones" if Player == "Velus Jones Jr."
replace Player = "Vernon Hargreaves" if Player == "Vernon Hargreaves III"
replace Player = "Villami Fehoko Jr." if Player == "Viliami Fehoko"
replace Player = "Vladimir Ducasse" if Player == "Vlad Ducasse"
replace Player = "Walter Powell" if Player == "Walt Powell"
replace Player = "Wan'dale Robinson" if Player == "Wan'Dale Robinson"
replace Player = "William Beatty" if Player == "Will Beatty"
replace Player = "Will Compton" if Player == "William Compton"
replace Player = "William Jackson" if Player == "William Jackson III"
replace Player = "Will Sherman" if Player == "William Sherman"
replace Player = "Willie Harvey Jr." if Player == "Willie Harvey"
replace Player = "Yannik Cudjoe-Virgil" if Player == "Yannick Cudjoe-Virgil"
replace Player = "Zac Diles" if Player == "Zach Diles"
replace Player = "Zachary Williams" if Player == "Zack Williams"
replace Player = "Ezekiel Turner" if Player == "Zeke Turner"

save "C:/Users/Owner/OneDrive/Documents/Georgetown University/Thesis Writer/Research/QB Worth/Game Analysis/Data 8 Injuries Clean.dta", replace