clear all
use "C:/Users/Owner/OneDrive/Documents/Georgetown University/Thesis Writer/Research/QB Worth/Game Analysis/Data 16 Merge Dataset.dta"
local Flag = 1
drop if TeamDum == 0

* Overall and NoQ4 stats
foreach y in "" "NoQ4" {
	* Game, sum, and omit stats
	foreach x in PassAtt PassCmp PassYds PassTD PassInt Sk SkYds RushAtt RushYds RushTD Fmb FL {
		* Stats for all the quarterbacks who played in each game
		egen GameQB`x'`y' = total(QB`x'`y'), by(Game)
		* Total stats for a quarterback on a team in a season
		egen SumQB`x'`y' = total(QB`x'`y'), by(FE Player)
		* Total stats minus game stats
		gen OmitQB`x'`y' = SumQB`x'`y' - QB`x'`y'
	}
	
	* Game and sum passer rating, ANY/A, TANY/A, and FP/A
	foreach x in Game Sum {
		gen a = (`x'QBPassCmp`y' / `x'QBPassAtt`y' - .3) * 5
		gen b = (`x'QBPassYds`y' / `x'QBPassAtt`y' - 3) * 0.25
		gen c = (`x'QBPassTD`y' / `x'QBPassAtt`y') * 20
		gen d = 2.375 - (`x'QBPassInt`y' / `x'QBPassAtt`y' * 25)
		replace a = 0 if a < 0
		replace a = 2.375 if a > 2.375
		replace b = 0 if b < 0
		replace b = 2.375 if b > 2.375
		replace c = 0 if c < 0
		replace c = 2.375 if c > 2.375
		replace d = 0 if d < 0
		replace d = 2.375 if d > 2.375
		gen `x'Rate`y' = (a + b + c + d) / 6 * 100
		drop a b c d
		
		gen `x'ANYA`y' = (`x'QBPassYds`y' - `x'QBSkYds`y' + 20 * `x'QBPassTD`y' - 45 * `x'QBPassInt`y') / (`x'QBPassAtt`y' + `x'QBSk`y')
		gen `x'TANYA`y' = (`x'QBPassYds`y' - `x'QBSkYds`y' + `x'QBRushYds`y' + 20 * (`x'QBPassTD`y' + `x'QBRushTD`y') - 45 * (`x'QBPassInt`y' + `x'QBFL`y')) / (`x'QBPassAtt`y' + `x'QBSk`y' + `x'QBRushAtt`y')
		gen `x'FPA`y' = (.04*`x'QBPassYds`y' + 4*`x'QBPassTD`y' - 2*`x'QBPassInt`y' + .1*`x'QBRushYds`y' + 6*`x'QBRushTD`y' - 2*`x'QBFL`y') / (`x'QBPassAtt`y' + `x'QBRushAtt`y')
	}
	label variable GameRate`y' "GameRate`y'"
	label variable GameANYA`y' "GameANYA`y'"
	label variable GameTANYA`y' "GameTANYA`y'"
	label variable GameFPA`y' "GameFPA`y'"

	* Weighted average passer rating, ANY/A, TANY/A, and FP/A
	egen SeasonRate`y' = total(QBPassAtt`y' / GameQBPassAtt`y' * SumRate`y'), by(Game)
	egen SeasonANYA`y' = total((QBPassAtt`y' + QBSk`y') / (GameQBPassAtt`y' + GameQBSk`y') * SumANYA`y'), by(Game)
	egen SeasonTANYA`y' = total((QBPassAtt`y' + QBSk`y' + QBRushAtt`y') / (GameQBPassAtt`y' + GameQBSk`y' + GameQBRushAtt`y') * SumTANYA`y'), by(Game)
	egen SeasonFPA`y' = total((QBPassAtt`y' + QBRushAtt`y') / (GameQBPassAtt`y' + GameQBRushAtt`y') * SumFPA`y'), by(Game)
	foreach x in Rate ANYA TANYA FPA {
		label variable Season`x'`y' "Season`x'`y'"
	}
}

* Determine if multiple QBs played in game
gen MultiFlag = 0
replace MultiFlag = 1 if QBPassAtt != GameQBPassAtt
label variable MultiFlag "MultiFlag"

* Generate AvgReport
egen AvgReport = total(Report * QBPassAtt / GameQBPassAtt), by(Game)
label variable AvgReport "AvgReport"

* Drop quarterbacks who aren't the primary quarterback (already sorted by QBPassAtt then QBPassCmp then QBRushAtt)
gen PrimaryDum = 0
local NObs = _N
forvalues i = 1/`NObs' {
	quietly replace PrimaryDum in `i' = 1 if Game[`i'] != Game[`i'-1]
}
label variable PrimaryDum "PrimaryDum"
drop if PrimaryDum == 0

* Rest days (2017 Dolphins-Buccaneers W1, 2020 Preseason, 2021 Saints-Cardinals P3, 2022 Bengals-Bills W17)
gen Preseason = ""

* Preseason is day of 2nd to last preseason game because starters sit last game
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Arizona Cardinals"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Atlanta Falcons"
quietly replace Preseason = "Thu" if Season == 2011 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Buffalo Bills"
quietly replace Preseason = "Thu" if Season == 2011 & Team == "Carolina Panthers"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Chicago Bears"
quietly replace Preseason = "Thu" if Season == 2011 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Thu" if Season == 2011 & Team == "Cleveland Browns"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Denver Broncos"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Detroit Lions"
quietly replace Preseason = "Fri" if Season == 2011 & Team == "Green Bay Packers"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Houston Texans"
quietly replace Preseason = "Fri" if Season == 2011 & Team == "Indianapolis Colts"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Fri" if Season == 2011 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Sun" if Season == 2011 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Fri" if Season == 2011 & Team == "Los Angeles Rams"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Miami Dolphins"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Minnesota Vikings"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "New England Patriots"
quietly replace Preseason = "Sun" if Season == 2011 & Team == "New Orleans Saints"
quietly replace Preseason = "Mon" if Season == 2011 & Team == "New York Giants"
quietly replace Preseason = "Mon" if Season == 2011 & Team == "New York Jets"
quietly replace Preseason = "Thu" if Season == 2011 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "San Francisco 49ers"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Seattle Seahawks"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sat" if Season == 2011 & Team == "Tennessee Titans"
quietly replace Preseason = "Thu" if Season == 2011 & Team == "Washington Commanders"

quietly replace Preseason = "Thu" if Season == 2012 & Team == "Arizona Cardinals"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Atlanta Falcons"
quietly replace Preseason = "Thu" if Season == 2012 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "Buffalo Bills"
quietly replace Preseason = "Sun" if Season == 2012 & Team == "Carolina Panthers"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Chicago Bears"
quietly replace Preseason = "Thu" if Season == 2012 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Cleveland Browns"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sun" if Season == 2012 & Team == "Denver Broncos"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "Detroit Lions"
quietly replace Preseason = "Thu" if Season == 2012 & Team == "Green Bay Packers"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "Houston Texans"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "Indianapolis Colts"
quietly replace Preseason = "Thu" if Season == 2012 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "Los Angeles Rams"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Miami Dolphins"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Minnesota Vikings"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "New England Patriots"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "New Orleans Saints"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "New York Giants"
quietly replace Preseason = "Sun" if Season == 2012 & Team == "New York Jets"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Sun" if Season == 2012 & Team == "San Francisco 49ers"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Seattle Seahawks"
quietly replace Preseason = "Fri" if Season == 2012 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Thu" if Season == 2012 & Team == "Tennessee Titans"
quietly replace Preseason = "Sat" if Season == 2012 & Team == "Washington Commanders"

quietly replace Preseason = "Sat" if Season == 2013 & Team == "Arizona Cardinals"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Atlanta Falcons"
quietly replace Preseason = "Thu" if Season == 2013 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Buffalo Bills"
quietly replace Preseason = "Thu" if Season == 2013 & Team == "Carolina Panthers"
quietly replace Preseason = "Fri" if Season == 2013 & Team == "Chicago Bears"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Cleveland Browns"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Denver Broncos"
quietly replace Preseason = "Thu" if Season == 2013 & Team == "Detroit Lions"
quietly replace Preseason = "Fri" if Season == 2013 & Team == "Green Bay Packers"
quietly replace Preseason = "Sun" if Season == 2013 & Team == "Houston Texans"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Indianapolis Colts"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Fri" if Season == 2013 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Los Angeles Rams"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Miami Dolphins"
quietly replace Preseason = "Sun" if Season == 2013 & Team == "Minnesota Vikings"
quietly replace Preseason = "Thu" if Season == 2013 & Team == "New England Patriots"
quietly replace Preseason = "Sun" if Season == 2013 & Team == "New Orleans Saints"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "New York Giants"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "New York Jets"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Sun" if Season == 2013 & Team == "San Francisco 49ers"
quietly replace Preseason = "Fri" if Season == 2013 & Team == "Seattle Seahawks"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Tennessee Titans"
quietly replace Preseason = "Sat" if Season == 2013 & Team == "Washington Commanders"

quietly replace Preseason = "Sun" if Season == 2014 & Team == "Arizona Cardinals"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Atlanta Falcons"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Buffalo Bills"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "Carolina Panthers"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "Chicago Bears"
quietly replace Preseason = "Sun" if Season == 2014 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Cleveland Browns"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Denver Broncos"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "Detroit Lions"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "Green Bay Packers"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Houston Texans"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Indianapolis Colts"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sun" if Season == 2014 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Los Angeles Rams"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Miami Dolphins"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Minnesota Vikings"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "New England Patriots"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "New Orleans Saints"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "New York Giants"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "New York Jets"
quietly replace Preseason = "Thu" if Season == 2014 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Thu" if Season == 2014 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Sun" if Season == 2014 & Team == "San Francisco 49ers"
quietly replace Preseason = "Fri" if Season == 2014 & Team == "Seattle Seahawks"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Tennessee Titans"
quietly replace Preseason = "Sat" if Season == 2014 & Team == "Washington Commanders"

quietly replace Preseason = "Sun" if Season == 2015 & Team == "Arizona Cardinals"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Atlanta Falcons"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Buffalo Bills"
quietly replace Preseason = "Fri" if Season == 2015 & Team == "Carolina Panthers"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Chicago Bears"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Cleveland Browns"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Denver Broncos"
quietly replace Preseason = "Fri" if Season == 2015 & Team == "Detroit Lions"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Green Bay Packers"
quietly replace Preseason = "Sun" if Season == 2015 & Team == "Houston Texans"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Indianapolis Colts"
quietly replace Preseason = "Fri" if Season == 2015 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Fri" if Season == 2015 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Sun" if Season == 2015 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Los Angeles Rams"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Miami Dolphins"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Minnesota Vikings"
quietly replace Preseason = "Fri" if Season == 2015 & Team == "New England Patriots"
quietly replace Preseason = "Sun" if Season == 2015 & Team == "New Orleans Saints"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "New York Giants"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "New York Jets"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "San Francisco 49ers"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Seattle Seahawks"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Fri" if Season == 2015 & Team == "Tennessee Titans"
quietly replace Preseason = "Sat" if Season == 2015 & Team == "Washington Commanders"

quietly replace Preseason = "Sun" if Season == 2016 & Team == "Arizona Cardinals"
quietly replace Preseason = "Thu" if Season == 2016 & Team == "Atlanta Falcons"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Baltimore Ravens"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "Buffalo Bills"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "Carolina Panthers"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Chicago Bears"
quietly replace Preseason = "Sun" if Season == 2016 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "Cleveland Browns"
quietly replace Preseason = "Thu" if Season == 2016 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Denver Broncos"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Detroit Lions"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "Green Bay Packers"
quietly replace Preseason = "Sun" if Season == 2016 & Team == "Houston Texans"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Indianapolis Colts"
quietly replace Preseason = "Sun" if Season == 2016 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sun" if Season == 2016 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Los Angeles Rams"
quietly replace Preseason = "Thu" if Season == 2016 & Team == "Miami Dolphins"
quietly replace Preseason = "Sun" if Season == 2016 & Team == "Minnesota Vikings"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "New England Patriots"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "New Orleans Saints"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "New York Giants"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "New York Jets"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "San Francisco 49ers"
quietly replace Preseason = "Thu" if Season == 2016 & Team == "Seattle Seahawks"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sat" if Season == 2016 & Team == "Tennessee Titans"
quietly replace Preseason = "Fri" if Season == 2016 & Team == "Washington Commanders"

quietly replace Preseason = "Sat" if Season == 2017 & Team == "Arizona Cardinals"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Atlanta Falcons"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Buffalo Bills"
quietly replace Preseason = "Thu" if Season == 2017 & Team == "Carolina Panthers"
quietly replace Preseason = "Sun" if Season == 2017 & Team == "Chicago Bears"
quietly replace Preseason = "Sun" if Season == 2017 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Cleveland Browns"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Denver Broncos"
quietly replace Preseason = "Fri" if Season == 2017 & Team == "Detroit Lions"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Green Bay Packers"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Houston Texans"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Indianapolis Colts"
quietly replace Preseason = "Thu" if Season == 2017 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Fri" if Season == 2017 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Los Angeles Rams"
quietly replace Preseason = "Thu" if Season == 2017 & Team == "Miami Dolphins"
quietly replace Preseason = "Sun" if Season == 2017 & Team == "Minnesota Vikings"
quietly replace Preseason = "Fri" if Season == 2017 & Team == "New England Patriots"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "New Orleans Saints"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "New York Giants"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "New York Jets"
quietly replace Preseason = "Thu" if Season == 2017 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Sun" if Season == 2017 & Team == "San Francisco 49ers"
quietly replace Preseason = "Fri" if Season == 2017 & Team == "Seattle Seahawks"
quietly replace Preseason = "Sat" if Season == 2017 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sun" if Season == 2017 & Team == "Tennessee Titans"
quietly replace Preseason = "Sun" if Season == 2017 & Team == "Washington Commanders"

quietly replace Preseason = "Sun" if Season == 2018 & Team == "Arizona Cardinals"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Atlanta Falcons"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sun" if Season == 2018 & Team == "Buffalo Bills"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "Carolina Panthers"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Chicago Bears"
quietly replace Preseason = "Sun" if Season == 2018 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Thu" if Season == 2018 & Team == "Cleveland Browns"
quietly replace Preseason = "Sun" if Season == 2018 & Team == "Dallas Cowboys"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "Denver Broncos"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "Detroit Lions"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "Green Bay Packers"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Houston Texans"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Indianapolis Colts"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Los Angeles Rams"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Miami Dolphins"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "Minnesota Vikings"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "New England Patriots"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "New Orleans Saints"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "New York Giants"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "New York Jets"
quietly replace Preseason = "Thu" if Season == 2018 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "San Francisco 49ers"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "Seattle Seahawks"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sat" if Season == 2018 & Team == "Tennessee Titans"
quietly replace Preseason = "Fri" if Season == 2018 & Team == "Washington Commanders"

quietly replace Preseason = "Sat" if Season == 2019 & Team == "Arizona Cardinals"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Atlanta Falcons"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Baltimore Ravens"
quietly replace Preseason = "Fri" if Season == 2019 & Team == "Buffalo Bills"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Carolina Panthers"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Chicago Bears"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Fri" if Season == 2019 & Team == "Cleveland Browns"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Denver Broncos"
quietly replace Preseason = "Fri" if Season == 2019 & Team == "Detroit Lions"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Green Bay Packers"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Houston Texans"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Indianapolis Colts"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Los Angeles Rams"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Miami Dolphins"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Minnesota Vikings"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "New England Patriots"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "New Orleans Saints"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "New York Giants"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "New York Jets"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Sun" if Season == 2019 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "San Francisco 49ers"
quietly replace Preseason = "Sat" if Season == 2019 & Team == "Seattle Seahawks"
quietly replace Preseason = "Fri" if Season == 2019 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sun" if Season == 2019 & Team == "Tennessee Titans"
quietly replace Preseason = "Thu" if Season == 2019 & Team == "Washington Commanders"

quietly replace Preseason = "" if Season == 2020 & Team == "Arizona Cardinals"
quietly replace Preseason = "" if Season == 2020 & Team == "Atlanta Falcons"
quietly replace Preseason = "" if Season == 2020 & Team == "Baltimore Ravens"
quietly replace Preseason = "" if Season == 2020 & Team == "Buffalo Bills"
quietly replace Preseason = "" if Season == 2020 & Team == "Carolina Panthers"
quietly replace Preseason = "" if Season == 2020 & Team == "Chicago Bears"
quietly replace Preseason = "" if Season == 2020 & Team == "Cincinnati Bengals"
quietly replace Preseason = "" if Season == 2020 & Team == "Cleveland Browns"
quietly replace Preseason = "" if Season == 2020 & Team == "Dallas Cowboys"
quietly replace Preseason = "" if Season == 2020 & Team == "Denver Broncos"
quietly replace Preseason = "" if Season == 2020 & Team == "Detroit Lions"
quietly replace Preseason = "" if Season == 2020 & Team == "Green Bay Packers"
quietly replace Preseason = "" if Season == 2020 & Team == "Houston Texans"
quietly replace Preseason = "" if Season == 2020 & Team == "Indianapolis Colts"
quietly replace Preseason = "" if Season == 2020 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "" if Season == 2020 & Team == "Kansas City Chiefs"
quietly replace Preseason = "" if Season == 2020 & Team == "Las Vegas Raiders"
quietly replace Preseason = "" if Season == 2020 & Team == "Los Angeles Chargers"
quietly replace Preseason = "" if Season == 2020 & Team == "Los Angeles Rams"
quietly replace Preseason = "" if Season == 2020 & Team == "Miami Dolphins"
quietly replace Preseason = "" if Season == 2020 & Team == "Minnesota Vikings"
quietly replace Preseason = "" if Season == 2020 & Team == "New England Patriots"
quietly replace Preseason = "" if Season == 2020 & Team == "New Orleans Saints"
quietly replace Preseason = "" if Season == 2020 & Team == "New York Giants"
quietly replace Preseason = "" if Season == 2020 & Team == "New York Jets"
quietly replace Preseason = "" if Season == 2020 & Team == "Philadelphia Eagles"
quietly replace Preseason = "" if Season == 2020 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "" if Season == 2020 & Team == "San Francisco 49ers"
quietly replace Preseason = "" if Season == 2020 & Team == "Seattle Seahawks"
quietly replace Preseason = "" if Season == 2020 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "" if Season == 2020 & Team == "Tennessee Titans"
quietly replace Preseason = "" if Season == 2020 & Team == "Washington Commanders"

quietly replace Preseason = "" if Season == 2021 & Team == "Arizona Cardinals"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "Atlanta Falcons"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Buffalo Bills"
quietly replace Preseason = "Fri" if Season == 2021 & Team == "Carolina Panthers"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Chicago Bears"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "Cleveland Browns"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Denver Broncos"
quietly replace Preseason = "Fri" if Season == 2021 & Team == "Detroit Lions"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Green Bay Packers"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Houston Texans"
quietly replace Preseason = "Fri" if Season == 2021 & Team == "Indianapolis Colts"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Fri" if Season == 2021 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Los Angeles Rams"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "Miami Dolphins"
quietly replace Preseason = "Fri" if Season == 2021 & Team == "Minnesota Vikings"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "New England Patriots"
quietly replace Preseason = "" if Season == 2021 & Team == "New Orleans Saints"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "New York Giants"
quietly replace Preseason = "Fri" if Season == 2021 & Team == "New York Jets"
quietly replace Preseason = "Fri" if Season == 2021 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Fri" if Season == 2021 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Sun" if Season == 2021 & Team == "San Francisco 49ers"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Seattle Seahawks"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Tennessee Titans"
quietly replace Preseason = "Sat" if Season == 2021 & Team == "Washington Commanders"

quietly replace Preseason = "Sat" if Season == 2022 & Team == "Arizona Cardinals"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Atlanta Falcons"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Baltimore Ravens"
quietly replace Preseason = "Fri" if Season == 2022 & Team == "Buffalo Bills"
quietly replace Preseason = "Fri" if Season == 2022 & Team == "Carolina Panthers"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Chicago Bears"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Cleveland Browns"
quietly replace Preseason = "Fri" if Season == 2022 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Denver Broncos"
quietly replace Preseason = "Sun" if Season == 2022 & Team == "Detroit Lions"
quietly replace Preseason = "Thu" if Season == 2022 & Team == "Green Bay Packers"
quietly replace Preseason = "Thu" if Season == 2022 & Team == "Houston Texans"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Indianapolis Colts"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Thu" if Season == 2022 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Fri" if Season == 2022 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Fri" if Season == 2022 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Los Angeles Rams"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Miami Dolphins"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Minnesota Vikings"
quietly replace Preseason = "Fri" if Season == 2022 & Team == "New England Patriots"
quietly replace Preseason = "Fri" if Season == 2022 & Team == "New Orleans Saints"
quietly replace Preseason = "Sun" if Season == 2022 & Team == "New York Giants"
quietly replace Preseason = "Sun" if Season == 2022 & Team == "New York Jets"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Sun" if Season == 2022 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Thu" if Season == 2022 & Team == "San Francisco 49ers"
quietly replace Preseason = "Fri" if Season == 2022 & Team == "Seattle Seahawks"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Tennessee Titans"
quietly replace Preseason = "Sat" if Season == 2022 & Team == "Washington Commanders"

quietly replace Preseason = "Sat" if Season == 2023 & Team == "Arizona Cardinals"
quietly replace Preseason = "Thu" if Season == 2023 & Team == "Atlanta Falcons"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Buffalo Bills"
quietly replace Preseason = "Fri" if Season == 2023 & Team == "Carolina Panthers"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Chicago Bears"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Cleveland Browns"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Denver Broncos"
quietly replace Preseason = "Fri" if Season == 2023 & Team == "Detroit Lions"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Green Bay Packers"
quietly replace Preseason = "Sun" if Season == 2023 & Team == "Houston Texans"
quietly replace Preseason = "Thu" if Season == 2023 & Team == "Indianapolis Colts"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Fri" if Season == 2023 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Los Angeles Rams"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Miami Dolphins"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Minnesota Vikings"
quietly replace Preseason = "Fri" if Season == 2023 & Team == "New England Patriots"
quietly replace Preseason = "Sun" if Season == 2023 & Team == "New Orleans Saints"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "New York Giants"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "New York Jets"
quietly replace Preseason = "Thu" if Season == 2023 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Thu" if Season == 2023 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Fri" if Season == 2023 & Team == "San Francisco 49ers"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Seattle Seahawks"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Fri" if Season == 2023 & Team == "Tennessee Titans"
quietly replace Preseason = "Sat" if Season == 2023 & Team == "Washington Commanders"

quietly replace Preseason = "Sun" if Season == 2024 & Team == "Arizona Cardinals"
quietly replace Preseason = "Fri" if Season == 2024 & Team == "Atlanta Falcons"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Baltimore Ravens"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Buffalo Bills"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Carolina Panthers"
quietly replace Preseason = "Thu" if Season == 2024 & Team == "Chicago Bears"
quietly replace Preseason = "Thu" if Season == 2024 & Team == "Cincinnati Bengals"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Cleveland Browns"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Dallas Cowboys"
quietly replace Preseason = "Sun" if Season == 2024 & Team == "Denver Broncos"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Detroit Lions"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Green Bay Packers"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Houston Texans"
quietly replace Preseason = "Thu" if Season == 2024 & Team == "Indianapolis Colts"
quietly replace Preseason = "Fri" if Season == 2024 & Team == "Jacksonville Jaguars"
quietly replace Preseason = "Thu" if Season == 2024 & Team == "Kansas City Chiefs"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Las Vegas Raiders"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Los Angeles Chargers"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Los Angeles Rams"
quietly replace Preseason = "Fri" if Season == 2024 & Team == "Miami Dolphins"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Minnesota Vikings"
quietly replace Preseason = "Sun" if Season == 2024 & Team == "New England Patriots"
quietly replace Preseason = "Sun" if Season == 2024 & Team == "New Orleans Saints"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "New York Giants"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "New York Jets"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Philadelphia Eagles"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Pittsburgh Steelers"
quietly replace Preseason = "Fri" if Season == 2024 & Team == "San Francisco 49ers"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Seattle Seahawks"
quietly replace Preseason = "Fri" if Season == 2024 & Team == "Tampa Bay Buccaneers"
quietly replace Preseason = "Sat" if Season == 2024 & Team == "Tennessee Titans"
quietly replace Preseason = "Sun" if Season == 2024 & Team == "Washington Commanders"

* Generate OppPreseason
gen OppPreseason = ""

quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Thu" if Season == 2011 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Thu" if Season == 2011 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Thu" if Season == 2011 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Thu" if Season == 2011 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Fri" if Season == 2011 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Houston Texans"
quietly replace OppPreseason = "Fri" if Season == 2011 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Fri" if Season == 2011 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Sun" if Season == 2011 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Fri" if Season == 2011 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sun" if Season == 2011 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Mon" if Season == 2011 & Opp == "New York Giants"
quietly replace OppPreseason = "Mon" if Season == 2011 & Opp == "New York Jets"
quietly replace OppPreseason = "Thu" if Season == 2011 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sat" if Season == 2011 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Thu" if Season == 2011 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Thu" if Season == 2012 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Thu" if Season == 2012 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Sun" if Season == 2012 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Thu" if Season == 2012 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sun" if Season == 2012 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Thu" if Season == 2012 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "Houston Texans"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Thu" if Season == 2012 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "New York Giants"
quietly replace OppPreseason = "Sun" if Season == 2012 & Opp == "New York Jets"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Sun" if Season == 2012 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Fri" if Season == 2012 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Thu" if Season == 2012 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Sat" if Season == 2012 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Thu" if Season == 2013 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Thu" if Season == 2013 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Fri" if Season == 2013 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Thu" if Season == 2013 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Fri" if Season == 2013 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sun" if Season == 2013 & Opp == "Houston Texans"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Fri" if Season == 2013 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sun" if Season == 2013 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Thu" if Season == 2013 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sun" if Season == 2013 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "New York Giants"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "New York Jets"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Sun" if Season == 2013 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Fri" if Season == 2013 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Sat" if Season == 2013 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sun" if Season == 2014 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Sun" if Season == 2014 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Houston Texans"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sun" if Season == 2014 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "New York Giants"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "New York Jets"
quietly replace OppPreseason = "Thu" if Season == 2014 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Thu" if Season == 2014 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Sun" if Season == 2014 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Fri" if Season == 2014 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Sat" if Season == 2014 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sun" if Season == 2015 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Fri" if Season == 2015 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Fri" if Season == 2015 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sun" if Season == 2015 & Opp == "Houston Texans"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Fri" if Season == 2015 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Fri" if Season == 2015 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Sun" if Season == 2015 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Fri" if Season == 2015 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sun" if Season == 2015 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "New York Giants"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "New York Jets"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Fri" if Season == 2015 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Sat" if Season == 2015 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sun" if Season == 2016 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Thu" if Season == 2016 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Sun" if Season == 2016 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Thu" if Season == 2016 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sun" if Season == 2016 & Opp == "Houston Texans"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Sun" if Season == 2016 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sun" if Season == 2016 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Thu" if Season == 2016 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sun" if Season == 2016 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "New England Patriots"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "New York Giants"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "New York Jets"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Thu" if Season == 2016 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sat" if Season == 2016 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Fri" if Season == 2016 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Thu" if Season == 2017 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Sun" if Season == 2017 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Sun" if Season == 2017 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Fri" if Season == 2017 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Houston Texans"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Thu" if Season == 2017 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Fri" if Season == 2017 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Thu" if Season == 2017 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sun" if Season == 2017 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Fri" if Season == 2017 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "New York Giants"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "New York Jets"
quietly replace OppPreseason = "Thu" if Season == 2017 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Sun" if Season == 2017 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Fri" if Season == 2017 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Sat" if Season == 2017 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sun" if Season == 2017 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Sun" if Season == 2017 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sun" if Season == 2018 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sun" if Season == 2018 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Sun" if Season == 2018 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Thu" if Season == 2018 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sun" if Season == 2018 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Houston Texans"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "New York Giants"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "New York Jets"
quietly replace OppPreseason = "Thu" if Season == 2018 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sat" if Season == 2018 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Fri" if Season == 2018 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Fri" if Season == 2019 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Fri" if Season == 2019 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Fri" if Season == 2019 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Houston Texans"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "New York Giants"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "New York Jets"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Sun" if Season == 2019 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Sat" if Season == 2019 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Fri" if Season == 2019 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sun" if Season == 2019 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Thu" if Season == 2019 & Opp == "Washington Commanders"

quietly replace OppPreseason = "" if Season == 2020 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Chicago Bears"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Denver Broncos"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Detroit Lions"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Houston Texans"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "New England Patriots"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "New York Giants"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "New York Jets"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "" if Season == 2020 & Opp == "Washington Commanders"

quietly replace OppPreseason = "" if Season == 2021 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Fri" if Season == 2021 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Fri" if Season == 2021 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Houston Texans"
quietly replace OppPreseason = "Fri" if Season == 2021 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Fri" if Season == 2021 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Fri" if Season == 2021 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "New England Patriots"
quietly replace OppPreseason = "" if Season == 2021 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "New York Giants"
quietly replace OppPreseason = "Fri" if Season == 2021 & Opp == "New York Jets"
quietly replace OppPreseason = "Fri" if Season == 2021 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Fri" if Season == 2021 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Sun" if Season == 2021 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Sat" if Season == 2021 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Fri" if Season == 2022 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Fri" if Season == 2022 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Fri" if Season == 2022 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Sun" if Season == 2022 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Thu" if Season == 2022 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Thu" if Season == 2022 & Opp == "Houston Texans"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Thu" if Season == 2022 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Fri" if Season == 2022 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Fri" if Season == 2022 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Fri" if Season == 2022 & Opp == "New England Patriots"
quietly replace OppPreseason = "Fri" if Season == 2022 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Sun" if Season == 2022 & Opp == "New York Giants"
quietly replace OppPreseason = "Sun" if Season == 2022 & Opp == "New York Jets"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Sun" if Season == 2022 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Thu" if Season == 2022 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Fri" if Season == 2022 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Sat" if Season == 2022 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Thu" if Season == 2023 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Fri" if Season == 2023 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Fri" if Season == 2023 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sun" if Season == 2023 & Opp == "Houston Texans"
quietly replace OppPreseason = "Thu" if Season == 2023 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Fri" if Season == 2023 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Fri" if Season == 2023 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sun" if Season == 2023 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "New York Giants"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "New York Jets"
quietly replace OppPreseason = "Thu" if Season == 2023 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Thu" if Season == 2023 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Fri" if Season == 2023 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Fri" if Season == 2023 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Sat" if Season == 2023 & Opp == "Washington Commanders"

quietly replace OppPreseason = "Sun" if Season == 2024 & Opp == "Arizona Cardinals"
quietly replace OppPreseason = "Fri" if Season == 2024 & Opp == "Atlanta Falcons"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Baltimore Ravens"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Buffalo Bills"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Carolina Panthers"
quietly replace OppPreseason = "Thu" if Season == 2024 & Opp == "Chicago Bears"
quietly replace OppPreseason = "Thu" if Season == 2024 & Opp == "Cincinnati Bengals"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Cleveland Browns"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Dallas Cowboys"
quietly replace OppPreseason = "Sun" if Season == 2024 & Opp == "Denver Broncos"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Detroit Lions"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Green Bay Packers"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Houston Texans"
quietly replace OppPreseason = "Thu" if Season == 2024 & Opp == "Indianapolis Colts"
quietly replace OppPreseason = "Fri" if Season == 2024 & Opp == "Jacksonville Jaguars"
quietly replace OppPreseason = "Thu" if Season == 2024 & Opp == "Kansas City Chiefs"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Las Vegas Raiders"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Los Angeles Chargers"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Los Angeles Rams"
quietly replace OppPreseason = "Fri" if Season == 2024 & Opp == "Miami Dolphins"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Minnesota Vikings"
quietly replace OppPreseason = "Sun" if Season == 2024 & Opp == "New England Patriots"
quietly replace OppPreseason = "Sun" if Season == 2024 & Opp == "New Orleans Saints"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "New York Giants"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "New York Jets"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Philadelphia Eagles"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Pittsburgh Steelers"
quietly replace OppPreseason = "Fri" if Season == 2024 & Opp == "San Francisco 49ers"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Seattle Seahawks"
quietly replace OppPreseason = "Fri" if Season == 2024 & Opp == "Tampa Bay Buccaneers"
quietly replace OppPreseason = "Sat" if Season == 2024 & Opp == "Tennessee Titans"
quietly replace OppPreseason = "Sun" if Season == 2024 & Opp == "Washington Commanders"

* Generate RestDays
local NObs = _N
gen RestDays = .
forvalues i = 1/`NObs' {
	quietly replace RestDays = Date[`i'] - Date[`i' - 1] - 1 in `i' if Week != 1
}

quietly replace RestDays = 13 if Week == 1 & Preseason == "Thu" & Day == "Thu"
quietly replace RestDays = 16 if Week == 1 & Preseason == "Thu" & Day == "Sun"
quietly replace RestDays = 17 if Week == 1 & Preseason == "Thu" & Day == "Mon"

quietly replace RestDays = 12 if Week == 1 & Preseason == "Fri" & Day == "Thu"
quietly replace RestDays = 15 if Week == 1 & Preseason == "Fri" & Day == "Sun"
quietly replace RestDays = 16 if Week == 1 & Preseason == "Fri" & Day == "Mon"

quietly replace RestDays = 11 if Week == 1 & Preseason == "Sat" & Day == "Thu"
quietly replace RestDays = 14 if Week == 1 & Preseason == "Sat" & Day == "Sun"
quietly replace RestDays = 15 if Week == 1 & Preseason == "Sat" & Day == "Mon"

quietly replace RestDays = 10 if Week == 1 & Preseason == "Sun" & Day == "Thu"
quietly replace RestDays = 13 if Week == 1 & Preseason == "Sun" & Day == "Sun"
quietly replace RestDays = 14 if Week == 1 & Preseason == "Sun" & Day == "Mon"

quietly replace RestDays =  9 if Week == 1 & Preseason == "Mon" & Day == "Thu"
quietly replace RestDays = 12 if Week == 1 & Preseason == "Mon" & Day == "Sun"
quietly replace RestDays = 13 if Week == 1 & Preseason == "Mon" & Day == "Mon"

quietly replace RestDays = 11 if Week == 1 & Preseason == "Fri" & Day == "Wed"
quietly replace RestDays = 10 if Week == 1 & Preseason == "Sat" & Day == "Wed"
quietly replace RestDays = 12 if Week == 1 & Preseason == "Sat" & Day == "Fri"

quietly replace RestDays = 17 if Week == 1 & Preseason == ""
quietly replace RestDays = 17 if Week == 2 & (Team == "Miami Dolphins" | Team == "Tampa Bay Buccaneers") & Season == 2017
quietly replace RestDays =  5 if Week == 18 & (Team == "Cincinnati Bengals" | Team == "Buffalo Bills") & Season == 2022
label variable RestDays "RestDays"

* Generate OppRestDays
sort Opp Season Week
gen OppRestDays = .
forvalues i = 1/`NObs' {
	quietly replace OppRestDays = Date[`i'] - Date[ `i' - 1] - 1 in `i' if Week != 1
}

quietly replace OppRestDays = 13 if Week == 1 & OppPreseason == "Thu" & Day == "Thu"
quietly replace OppRestDays = 16 if Week == 1 & OppPreseason == "Thu" & Day == "Sun"
quietly replace OppRestDays = 17 if Week == 1 & OppPreseason == "Thu" & Day == "Mon"

quietly replace OppRestDays = 12 if Week == 1 & OppPreseason == "Fri" & Day == "Thu"
quietly replace OppRestDays = 15 if Week == 1 & OppPreseason == "Fri" & Day == "Sun"
quietly replace OppRestDays = 16 if Week == 1 & OppPreseason == "Fri" & Day == "Mon"

quietly replace OppRestDays = 11 if Week == 1 & OppPreseason == "Sat" & Day == "Thu"
quietly replace OppRestDays = 14 if Week == 1 & OppPreseason == "Sat" & Day == "Sun"
quietly replace OppRestDays = 15 if Week == 1 & OppPreseason == "Sat" & Day == "Mon"

quietly replace OppRestDays = 10 if Week == 1 & OppPreseason == "Sun" & Day == "Thu"
quietly replace OppRestDays = 13 if Week == 1 & OppPreseason == "Sun" & Day == "Sun"
quietly replace OppRestDays = 14 if Week == 1 & OppPreseason == "Sun" & Day == "Mon"

quietly replace OppRestDays =  9 if Week == 1 & OppPreseason == "Mon" & Day == "Thu"
quietly replace OppRestDays = 12 if Week == 1 & OppPreseason == "Mon" & Day == "Sun"
quietly replace OppRestDays = 13 if Week == 1 & OppPreseason == "Mon" & Day == "Mon"

quietly replace OppRestDays = 11 if Week == 1 & OppPreseason == "Fri" & Day == "Wed"
quietly replace OppRestDays = 10 if Week == 1 & OppPreseason == "Sat" & Day == "Wed"
quietly replace OppRestDays = 12 if Week == 1 & OppPreseason == "Sat" & Day == "Fri"

quietly replace OppRestDays = 17 if Week == 1 & OppPreseason == ""
quietly replace OppRestDays = 17 if Week == 2 & (Opp == "Miami Dolphins" | Opp == "Tampa Bay Buccaneers") & Season == 2017
quietly replace OppRestDays =  5 if Week == 18 & (Opp == "Cincinnati Bengals" | Opp == "Buffalo Bills") & Season == 2022

label variable OppRestDays "OppRestDays"
sort Team Season Week
drop Preseason OppPreseason

* Rookie season
gen RookieSeason = .
replace RookieSeason = 1995 if Player == "Kerry Collins"
replace RookieSeason = 1996 if Player == "Jon Kitna"
replace RookieSeason = 1997 if Player == "Jake Delhomme"
replace RookieSeason = 1998 if Player == "Charlie Batch" | Player == "Matt Hasselbeck" | Player == "Peyton Manning"
replace RookieSeason = 1999 if Player == "Donovan McNabb"
replace RookieSeason = 2000 if Player == "Billy Volek" | Player == "Chris Redman" | Player == "Tom Brady"
replace RookieSeason = 2001 if Player == "A.J. Feeley" | Player == "Drew Brees" | Player == "Michael Vick"
replace RookieSeason = 2002 if Player == "David Carr" | Player == "Josh McCown" | Player == "Shaun Hill"
replace RookieSeason = 2003 if Player == "Byron Leftwich" | Player == "Carson Palmer" | Player == "Kyle Boller" | Player == "Rex Grossman" | Player == "Seneca Wallace" | Player == "Tony Romo"
replace RookieSeason = 2004 if Player == "Ben Roethlisberger" | Player == "Eli Manning" | Player == "J.P. Losman" | Player == "Luke McCown" | Player == "Matt Schaub" | Player == "Philip Rivers"
replace RookieSeason = 2005 if Player == "Aaron Rodgers" | Player == "Alex Smith" | Player == "Dan Orlovsky" | Player == "Derek Anderson" | Player == "Jason Campbell" | Player == "Kyle Orton" | Player == "Matt Cassel" | Player == "Ryan Fitzpatrick"
replace RookieSeason = 2006 if Player == "Bruce Gradkowski" | Player == "Charlie Whitehurst" | Player == "Jay Cutler" | Player == "Kellen Clemens" | Player == "Matt Leinart" | Player == "Tarvaris Jackson" | Player == "Vince Young"
replace RookieSeason = 2007 if Player == "Brady Quinn" | Player == "Drew Stanton" | Player == "Kevin Kolb" | Player == "John Beck" | Player == "Matt Moore" | Player == "Tyler Palko" | Player == "Tyler Thigpen"
replace RookieSeason = 2008 if Player == "Caleb Hanie" | Player == "Chad Henne" | Player == "Joe Flacco" | Player == "Josh Johnson" | Player == "Matt Flynn" | Player == "Matt Ryan"
replace RookieSeason = 2009 if Player == "Brian Hoyer" | Player == "Chase Daniel" | Player == "Curtis Painter" | Player == "Graham Harrell" | Player == "Josh Freeman" | Player == "Mark Sanchez" | Player == "Matthew Stafford" | Player == "Stephen McGee" | Player == "Tom Brandstater"
replace RookieSeason = 2010 if Player == "Armanti Edwards" | Player == "Colt McCoy" | Player == "Jimmy Clausen" | Player == "Joe Webb" | Player == "John Skelton" | Player == "Mike Kafka" | Player == "Rusty Smith" | Player == "Sam Bradford" | Player == "Thaddeus Lewis" | Player == "Tim Tebow"
replace RookieSeason = 2011 if Player == "Andy Dalton" | Player == "Blaine Gabbert" | Player == "Cam Newton" | Player == "Christian Ponder" | Player == "Colin Kaepernick" | Player == "Greg McElroy" | Player == "Jake Locker" | Player == "Ryan Mallett" | Player == "Scott Tolzien" | Player == "T.J. Yates" | Player == "Terrelle Pryor" | Player == "Tyrod Taylor"
replace RookieSeason = 2012 if Player == "Alex Tanney" | Player == "Andrew Luck" | Player == "Austin Davis" | Player == "Brandon Weeden" | Player == "Brock Osweiler" | Player == "Case Keenum" | Player == "Dominique Davis" | Player == "Kellen Moore" | Player == "Kirk Cousins" | Player == "Matt Simms" | Player == "Nick Foles" | Player == "Robert Griffin III" | Player == "Russell Wilson" | Player == "Ryan Lindley" | Player == "Ryan Tannehill"
replace RookieSeason = 2013 if Player == "B.J. Daniels" | Player == "EJ Manuel" | Player == "Geno Smith" | Player == "Jeff Tuel" | Player == "Landry Jones" | Player == "Matt Barkley" | Player == "Matt McGloin" | Player == "Mike Glennon" | Player == "Ryan Griffin" | Player == "Ryan Nassib" | Player == "Tyler Bray"
replace RookieSeason = 2014 if Player == "A.J. McCarron" | Player == "Blake Bortles" | Player == "Connor Shaw" | Player == "David Fales" | Player == "Derek Carr" | Player == "Garrett Gilbert" | Player == "Jimmy Garoppolo" | Player == "Johnny Manziel" | Player == "Logan Thomas" | Player == "Teddy Bridgewater" | Player == "Tom Savage" | Player == "Zach Mettenberger"
replace RookieSeason = 2015 if Player == "Brett Hundley" | Player == "Bryce Petty" | Player == "Jameis Winston" | Player == "Marcus Mariota" | Player == "Sean Mannion" | Player == "Taylor Heinicke" | Player == "Trevor Siemian"
replace RookieSeason = 2016 if Player == "Brandon Allen" | Player == "Carson Wentz" | Player == "Cody Kessler" | Player == "Connor Cook" | Player == "Dak Prescott" | Player == "Jacoby Brissett" | Player == "Jared Goff" | Player == "Jeff Driskel" | Player == "Kevin Hogan" | Player == "Nate Sudfeld" | Player == "Paxton Lynch" | Player == "Trevone Boykin"
replace RookieSeason = 2017 if Player == "C.J. Beathard" | Player == "Cooper Rush" | Player == "Davis Webb" | Player == "Deshaun Watson" | Player == "DeShone Kizer" | Player == "Joshua Dobbs" | Player == "Mitchell Trubisky" | Player == "Nathan Peterman" | Player == "Nick Mullens" | Player == "P.J. Walker" | Player == "Patrick Mahomes" | Player == "Taysom Hill"
replace RookieSeason = 2018 if Player == "Baker Mayfield" | Player == "Chris Streveler" | Player == "John Wolford" | Player == "Josh Allen" | Player == "Josh Rosen" | Player == "Kurt Benkert" | Player == "Kyle Allen" | Player == "Lamar Jackson" | Player == "Logan Woodside" | Player == "Luke Falk" | Player == "Mason Rudolph" | Player == "Mike White" | Player == "Sam Darnold" | Player == "Tim Boyle"
replace RookieSeason = 2019 if Player == "Brett Rypien" | Player == "Daniel Jones" | Player == "David Blough" | Player == "Devlin Hodges" | Player == "Drew Lock" | Player == "Dwayne Haskins" | Player == "Easton Stick" | Player == "Gardner Minshew II" | Player == "Jake Browning" | Player == "Jarrett Stidham" | Player == "Kyler Murray" | Player == "Ryan Finley" | Player == "Trace McSorley" | Player == "Will Grier"
replace RookieSeason = 2020 if Player == "Ben DiNucci" | Player == "Bryce Perkins" | Player == "Jacob Eason" | Player == "Jake Fromm" | Player == "Jake Luton" | Player == "Jalen Hurts" | Player == "Joe Burrow" | Player == "Jordan Love" | Player == "Justin Herbert" | Player == "Kendall Hinton" | Player == "Tua Tagovailoa" | Player == "Tyler Huntley"
replace RookieSeason = 2021 if Player == "Davis Mills" | Player == "Feleipe Franks" | Player == "Ian Book" | Player == "Justin Fields" | Player == "Kellen Mond" | Player == "Kyle Trask" | Player == "Mac Jones" | Player == "Sam Ehlinger" | Player == "Trevor Lawrence" | Player == "Trey Lance" | Player == "Zach Wilson"
replace RookieSeason = 2022 if Player == "Anthony Brown" | Player == "Bailey Zappe" | Player == "Brock Purdy" | Player == "Desmond Ridder" | Player == "Kenny Pickett" | Player == "Malik Willis" | Player == "Sam Howell" | Player == "Skylar Thompson"
replace RookieSeason = 2023 if Player == "Aidan O'Connell" | Player == "Anthony Richardson" | Player == "Bryce Young" | Player == "C.J. Stroud" | Player == "Clayton Tune" | Player == "Dorian Thompson-Robinson" | Player == "Hendon Hooker" | Player == "Jake Haener" | Player == "Jaren Hall" | Player == "Sean Clifford" | Player == "Tanner McKee" | Player == "Tommy DeVito" | Player == "Tyson Bagent" | Player == "Will Levis"
replace RookieSeason = 2024 if Player == "Bo Nix" | Player == "Caleb Williams" | Player == "Drake Maye" | Player == "Jayden Daniels" | Player == "Joe Milton" | Player == "Michael Penix" | Player == "Spencer Rattler"

* Calculate LagWinPct and PriorWinPct
sort FE Week
by FE: gen Wins = sum(Win)
by FE: gen Games = _n
gen WinPct = Wins / Games
by FE: gen LagWinPct = WinPct[_n-1]
replace LagWinPct = WinPct[_n-1] if Season != 2011 & FE[_n] != FE[_n-1]
drop Wins Games WinPct
order LagWinPct, after(Win)

replace LagWinPct = 5/16 if Season == 2011 & Week == 1 & Team == "Arizona Cardinals"
replace LagWinPct = 13/16 if Season == 2011 & Week == 1 & Team == "Atlanta Falcons"
replace LagWinPct = 12/16 if Season == 2011 & Week == 1 & Team == "Baltimore Ravens"
replace LagWinPct = 4/16 if Season == 2011 & Week == 1 & Team == "Buffalo Bills"
replace LagWinPct = 2/16 if Season == 2011 & Week == 1 & Team == "Carolina Panthers"
replace LagWinPct = 11/16 if Season == 2011 & Week == 1 & Team == "Chicago Bears"
replace LagWinPct = 4/16 if Season == 2011 & Week == 1 & Team == "Cincinnati Bengals"
replace LagWinPct = 5/16 if Season == 2011 & Week == 1 & Team == "Cleveland Browns"
replace LagWinPct = 6/16 if Season == 2011 & Week == 1 & Team == "Dallas Cowboys"
replace LagWinPct = 4/16 if Season == 2011 & Week == 1 & Team == "Denver Broncos"
replace LagWinPct = 6/16 if Season == 2011 & Week == 1 & Team == "Detroit Lions"
replace LagWinPct = 10/16 if Season == 2011 & Week == 1 & Team == "Green Bay Packers"
replace LagWinPct = 6/16 if Season == 2011 & Week == 1 & Team == "Houston Texans"
replace LagWinPct = 10/16 if Season == 2011 & Week == 1 & Team == "Indianapolis Colts"
replace LagWinPct = 8/16 if Season == 2011 & Week == 1 & Team == "Jacksonville Jaguars"
replace LagWinPct = 10/16 if Season == 2011 & Week == 1 & Team == "Kansas City Chiefs"
replace LagWinPct = 8/16 if Season == 2011 & Week == 1 & Team == "Las Vegas Raiders"
replace LagWinPct = 9/16 if Season == 2011 & Week == 1 & Team == "Los Angeles Chargers"
replace LagWinPct = 7/16 if Season == 2011 & Week == 1 & Team == "Los Angeles Rams"
replace LagWinPct = 7/16 if Season == 2011 & Week == 1 & Team == "Miami Dolphins"
replace LagWinPct = 6/16 if Season == 2011 & Week == 1 & Team == "Minnesota Vikings"
replace LagWinPct = 14/16 if Season == 2011 & Week == 1 & Team == "New England Patriots"
replace LagWinPct = 11/16 if Season == 2011 & Week == 1 & Team == "New Orleans Saints"
replace LagWinPct = 10/16 if Season == 2011 & Week == 1 & Team == "New York Giants"
replace LagWinPct = 11/16 if Season == 2011 & Week == 1 & Team == "New York Jets"
replace LagWinPct = 10/16 if Season == 2011 & Week == 1 & Team == "Philadelphia Eagles"
replace LagWinPct = 12/16 if Season == 2011 & Week == 1 & Team == "Pittsburgh Steelers"
replace LagWinPct = 6/16 if Season == 2011 & Week == 1 & Team == "San Francisco 49ers"
replace LagWinPct = 7/16 if Season == 2011 & Week == 1 & Team == "Seattle Seahawks"
replace LagWinPct = 10/16 if Season == 2011 & Week == 1 & Team == "Tampa Bay Buccaneers"
replace LagWinPct = 6/16 if Season == 2011 & Week == 1 & Team == "Tennessee Titans"
replace LagWinPct = 6/16 if Season == 2011 & Week == 1 & Team == "Washington Commanders"

bysort FE (Week): gen PriorWinPct = LagWinPct[1]
label variable LagWinPct "LagWinPct"
label variable PriorWinPct "PriorWinPct"

* Generate OppLagWinPct and OppPriorWinPct
local Variable LagWinPct PriorWinPct
foreach x in `Variable' {
	quietly gen Opp`x' = .
	local NRows = 800
	local NObs = _N
	local NCols = ceil(`NObs'/`NRows')

	*Sort dataset by Opp and store Variable as a matrix
	sort Opp Season Week
	matrix Matrix = J(`NRows',`NCols',.)
	forvalues i = 1/`NCols' {
		local Start = (`i'-1)*`NRows'+1
		
		forvalues j = 1/`NRows' {
			local Obs = `Start'+`j'-1
			if `Obs' <= `NObs' {
				matrix Matrix[`j',`i'] = `x'[`Obs']
			}
		}
	}

	*Sort dataset by Team and restore matrix as OppVariable
	sort Team Season Week
	local Obs = 1
	forvalues i = 1/`NCols' {
		forvalues j = 1/`NRows' {
			if `Obs' <= `NObs' {
				*Extract value from matrix and store it in OppVariable
				quietly replace Opp`x' = Matrix[`j',`i'] in `Obs'
				local Obs = `Obs'+1
			}
		}
	}
	label variable Opp`x' "Opp`x'"
}

* Super Bowl
gen SB = 0
replace SB = 1 if Team == "Green Bay Packers" & Season == 2011
replace SB = 1 if Team == "New York Giants" & Season == 2012
replace SB = 1 if Team == "Baltimore Ravens" & Season == 2013
replace SB = 1 if Team == "Seattle Seahawks" & Season == 2014
replace SB = 1 if Team == "New England Patriots" & Season == 2015
replace SB = 1 if Team == "Denver Broncos" & Season == 2016
replace SB = 1 if Team == "New England Patriots" & Season == 2017
replace SB = 1 if Team == "Philadelphia Eagles" & Season == 2018
replace SB = 1 if Team == "New England Patriots" & Season == 2019
replace SB = 1 if Team == "Kansas City Chiefs" & Season == 2020
replace SB = 1 if Team == "Tampa Bay Buccaneers" & Season == 2021
replace SB = 1 if Team == "Los Angeles Rams" & Season == 2022
replace SB = 1 if Team == "Kansas City Chiefs" & Season == 2023
replace SB = 1 if Team == "Kansas City Chiefs" & Season == 2024
label variable SB "SB"

gen OppSB = 0
replace OppSB = 1 if Opp == "Green Bay Packers" & Season == 2011
replace OppSB = 1 if Opp == "New York Giants" & Season == 2012
replace OppSB = 1 if Opp == "Baltimore Ravens" & Season == 2013
replace OppSB = 1 if Opp == "Seattle Seahawks" & Season == 2014
replace OppSB = 1 if Opp == "New England Patriots" & Season == 2015
replace OppSB = 1 if Opp == "Denver Broncos" & Season == 2016
replace OppSB = 1 if Opp == "New England Patriots" & Season == 2017
replace OppSB = 1 if Opp == "Philadelphia Eagles" & Season == 2018
replace OppSB = 1 if Opp == "New England Patriots" & Season == 2019
replace OppSB = 1 if Opp == "Kansas City Chiefs" & Season == 2020
replace OppSB = 1 if Opp == "Tampa Bay Buccaneers" & Season == 2021
replace OppSB = 1 if Opp == "Los Angeles Rams" & Season == 2022
replace OppSB = 1 if Opp == "Kansas City Chiefs" & Season == 2023
replace OppSB = 1 if Opp == "Kansas City Chiefs" & Season == 2024
label variable OppSB "OppSB"

* Drop QBs who didn't have enough experience
if `Flag' == 2 {
	gen Experience = Season - RookieSeason + 1
	drop if Experience < 2
	drop Experience
}

* Drop QBs who didn't have enough other starts
if `Flag' == 3 {
	drop if OmitQBPassAtt == 0 & OmitQBSk == 0 & OmitQBRushAtt == 0
	gen Ones = 1
	egen Counter = sum(Ones), by(FE Player)
	drop if Counter < 4
	drop Ones Counter
}

* Keep and order variables
keep FE Game Season Week GameID Team Opp Win Home OppHome logIM OpplogIM logWB OpplogWB SGini OppSGini SNSRatio OppSNSRatio NonQBFantPt OppNonQBFantPt OffNonQBFantPt OppOffNonQBFantPt DefSTFantPt OppDefSTFantPt RestDays OppRestDays SpLine OppSpLine LagWinPct OppLagWinPct PriorWinPct OppPriorWinPct SB OppSB Player AvgReport GameRate SeasonRate GameANYA SeasonANYA GameTANYA SeasonTANYA GameFPA SeasonFPA SeasonRateNoQ4 SeasonANYANoQ4 SeasonTANYANoQ4 SeasonFPANoQ4 MultiFlag
order FE Game Season Week GameID Team Opp Win Home OppHome logIM OpplogIM logWB OpplogWB SGini OppSGini SNSRatio OppSNSRatio NonQBFantPt OppNonQBFantPt OffNonQBFantPt OppOffNonQBFantPt DefSTFantPt OppDefSTFantPt RestDays OppRestDays SpLine OppSpLine LagWinPct OppLagWinPct PriorWinPct OppPriorWinPct SB OppSB Player AvgReport GameRate SeasonRate GameANYA SeasonANYA GameTANYA SeasonTANYA GameFPA SeasonFPA SeasonRateNoQ4 SeasonANYANoQ4 SeasonTANYANoQ4 SeasonFPANoQ4 MultiFlag, first

if `Flag' == 1 {
	save "C:/Users/Owner/OneDrive/Documents/Georgetown University/Thesis Writer/Research/QB Worth/Game Analysis/Data 17 Team Dataset.dta", replace
}
else if `Flag' == 2 {
	save "C:/Users/Owner/OneDrive/Documents/Georgetown University/Thesis Writer/Research/QB Worth/Game Analysis/Data 18 Team Dataset Vet.dta", replace
}
else if `Flag' == 3 {
	save "C:/Users/Owner/OneDrive/Documents/Georgetown University/Thesis Writer/Research/QB Worth/Game Analysis/Data 19 Team Dataset Four.dta", replace
}