clear all
use "C:/Users/Owner/OneDrive/Documents/Georgetown University/Thesis Writer/Research/QB Worth/Season Analysis/Data 5 Season AV.dta"

drop PlayID
replace Team = "Atlanta Falcons" if Team == "ATL"
replace Team = "Buffalo Bills" if Team == "BUF"
replace Team = "Carolina Panthers" if Team == "CAR"
replace Team = "Chicago Bears" if Team == "CHI"
replace Team = "Cincinnati Bengals" if Team == "CIN"
replace Team = "Cleveland Browns" if Team == "CLE"
replace Team = "Indianapolis Colts" if Team == "CLT"
replace Team = "Arizona Cardinals" if Team == "CRD"
replace Team = "Dallas Cowboys" if Team == "DAL"
replace Team = "Denver Broncos" if Team == "DEN"
replace Team = "Detroit Lions" if Team == "DET"
replace Team = "Green Bay Packers" if Team == "GNB"
replace Team = "Houston Texans" if Team == "HTX"
replace Team = "Jacksonville Jaguars" if Team == "JAX"
replace Team = "Kansas City Chiefs" if Team == "KAN"
replace Team = "Miami Dolphins" if Team == "MIA"
replace Team = "Minnesota Vikings" if Team == "MIN"
replace Team = "New Orleans Saints" if Team == "NOR"
replace Team = "New England Patriots" if Team == "NWE"
replace Team = "New York Giants" if Team == "NYG"
replace Team = "New York Jets" if Team == "NYJ"
replace Team = "Tennessee Titans" if Team == "OTI"
replace Team = "Philadelphia Eagles" if Team == "PHI"
replace Team = "Pittsburgh Steelers" if Team == "PIT"
replace Team = "Las Vegas Raiders" if Team == "RAI"
replace Team = "Los Angeles Rams" if Team == "RAM"
replace Team = "Baltimore Ravens" if Team == "RAV"
replace Team = "Los Angeles Chargers" if Team == "SDG"
replace Team = "Seattle Seahawks" if Team == "SEA"
replace Team = "San Francisco 49ers" if Team == "SFO"
replace Team = "Tampa Bay Buccaneers" if Team == "TAM"
replace Team = "Washington Commanders" if Team == "WAS"

foreach x in No Age G GS Wt AV Salary{
	quietly destring `x', replace
}
quietly replace Yrs = "0" if Yrs == "Rook"
quietly destring Yrs, replace
format BirthDate %td

gen Feet = ""
gen Inches = ""
split Ht, gen(SplitValues) parse("-")
replace Feet = SplitValues1
replace Inches = SplitValues2
destring Feet Inches, replace
gen HtInches = 12*Feet+Inches
drop Ht
rename HtInches Ht
label variable Ht "Ht"
order Ht, before(Wt)
drop SplitValues* Feet Inches

* Fix corrupted apostrophes
replace Player = subinstr(Player, "â€™", "'", .)

* Fix accented characters
replace Player = subinstr(Player, "Ã¡", "á", .)
replace Player = subinstr(Player, "Ã©", "é", .)
replace Player = subinstr(Player, "Ã¨", "è", .)
replace Player = subinstr(Player, "Ã­", "í", .)
replace Player = subinstr(Player, "Ã³", "ó", .)
replace Player = subinstr(Player, "Ãº", "ú", .)
replace Player = subinstr(Player, "Ã±", "ñ", .)
replace Player = subinstr(Player, "Ãœ", "Ü", .)
replace Player = subinstr(Player, "Ã‰", "É", .)
* replace Player = subinstr(Player, "Ã", "Á", .) // Often appears as standalone corruption

* Fix miscellaneous corruptions
replace Player = subinstr(Player, "Â", "", .)

gen Index = _n
label variable Index "Index"
order Index Team Season, first
sort Team Season Player Index

* Distinguish between two different players with same name (Pro Football Reference corrected Michael Carter)
replace Player = "Greg Jones RB" if Player == "Greg Jones" & Team == "Jacksonville Jaguars" & Season == 2012 & Pos == "RB"
replace Player = "Greg Jones MLB" if Player == "Greg Jones" & Team == "Jacksonville Jaguars" & Season == 2012 & Pos == "LB"
replace Player = "T.J. Carter CB" if Player == "T.J. Carter" & Team == "Los Angeles Rams" & Season == 2022 & Pos == "CB"
replace Player = "T.J. Carter DE" if Player == "T.J. Carter" & Team == "Los Angeles Rams" & Season == 2022 & Pos == "DE"
rename Pos PosAV
label variable PosAV "PosAV"

* Match names to Money dataset (Mulholland and Calvetti don't do this; see "2 Season Corrections.xlsx")
gen OldPlayer = Player
gen Flag = 1
if Flag == 1 {
	quietly replace Player = "Adrian Davis" if Player == "A.J. Davis"
	quietly replace Player = "A.J. Arcuri" if Player == "AJ Arcuri"
	quietly replace Player = "A.J. Barner" if Player == "AJ Barner"
	quietly replace Player = "A.J. Cole" if Player == "AJ Cole III"
	quietly replace Player = "A.J. Dillon" if Player == "AJ Dillon"
	quietly replace Player = "A.J. Finley" if Player == "AJ Finley"
	quietly replace Player = "A.J. Parker" if Player == "AJ Parker"
	quietly replace Player = "A.J. Terrell" if Player == "AJ Terrell"
	quietly replace Player = "Adam-Pacman Jones" if Player == "Adam Jones"
	quietly replace Player = "Alexander Green" if Player == "Alex Green"
	quietly replace Player = "Armani Taylor-Prioleau" if Player == "Alex Taylor-Prioleau"
	quietly replace Player = "A.J. Johnson" if Player == "Alexander Johnson"
	quietly replace Player = "Amaré Barno" if Player == "Amare Barno"
	quietly replace Player = "Andre Jones Jr." if Player == "Andre Jones"
	quietly replace Player = "Andrew Adam" if Player == "Andrew Adams" & Team == "New York Giants"
	quietly replace Player = "Andrew Booth Jr." if Player == "Andrew Booth"
	quietly replace Player = "Anthony Johnson Jr." if Player == "Anthony Johnson" & (Team == "Green Bay Packers" | Team == "New York Giants")
	quietly replace Player = "Anthony McFarland" if Player == "Anthony McFarland Jr."
	quietly replace Player = "Anthony Walker Jr." if Player == "Anthony Walker"
	quietly replace Player = "Audric Estimé" if Player == "Audric Estime"
	quietly replace Player = "Deji Olatoye" if Player == "Ayodeji Olatoye"
	quietly replace Player = "B.J Cunningham" if Player == "B.J. Cunningham"
	quietly replace Player = "B.J. Ojulari" if Player == "BJ Ojulari"
	quietly replace Player = "B.J. Thompson" if Player == "BJ Thompson"
	quietly replace Player = "Benjamin Braden" if Player == "Ben Braden"
	quietly replace Player = "Benjamin Ijalana" if Player == "Ben Ijalana"
	quietly replace Player = "Benjamin Watson" if Player == "Ben Watson"
	quietly replace Player = "Carlos Basham Jr." if Player == "Boogie Basham"
	quietly replace Player = "Brenton Cox Jr." if Player == "Brenton Cox"
	quietly replace Player = "Brian Robinson" if Player == "Brian Robinson Jr."
	quietly replace Player = "Brian Thomas Jr." if Player == "Brian Thomas"
	quietly replace Player = "Broderick Washington" if Player == "Broderick Washington Jr."
	quietly replace Player = "Bryce Tremayne" if Player == "Brycen Tremayne"
	quietly replace Player = "Ryan Cooper" if Player == "Bump Cooper"
	quietly replace Player = "Olubunmi Rotimi" if Player == "Bunmi Rotimi"
	quietly replace Player = "Christian Bryant" if Player == "C.B. Bryant"
	quietly replace Player = "Ceandris Brown" if Player == "C.C. Brown"
	quietly replace Player = "Chauncey Gardner-Johnson" if Player == "C.J. Gardner-Johnson"
	quietly replace Player = "Carnell Williams" if Player == "Cadillac Williams"
	quietly replace Player = "Calvin Austin" if Player == "Calvin Austin III"
	quietly replace Player = "Cameron Brown" if Player == "Cam Brown"
	quietly replace Player = "Cam Lewis" if Player == "Cameron Lewis"
	quietly replace Player = "Cam Thomas" if Player == "Cameron Thomas"
	quietly replace Player = "Carl Jones Jr." if Player == "Carl Jones"
	quietly replace Player = "Carlos Washington Jr." if Player == "Carlos Washington"
	quietly replace Player = "Cassanova Mckinzy" if Player == "Cassanova McKinzy"
	quietly replace Player = "Cedrick Wilson" if Player == "Cedrick Wilson Jr."
	quietly replace Player = "Charles Leno" if Player == "Charles Leno Jr."
	quietly replace Player = "Charlie Thomas III" if Player == "Charlie Thomas"
	quietly replace Player = "Chig Okonkwo" if Player == "Chigoziem Okonkwo"
	quietly replace Player = "Christopher Carson" if Player == "Chris Carson"
	quietly replace Player = "Christopher Conte" if Player == "Chris Conte"
	quietly replace Player = "Chris Harris" if Player == "Chris Harris Jr."
	quietly replace Player = "Christopher Owens" if Player == "Chris Owens"
	quietly replace Player = "Chris Rodriguez Jr." if Player == "Chris Rodriguez"
	quietly replace Player = "Chris Rumph II" if Player == "Chris Rumph"
	quietly replace Player = "Christian Dilauro" if Player == "Christian DiLauro"
	quietly replace Player = "Chris Milton" if Player == "Christopher Milton"
	quietly replace Player = "Christopher Smith II" if Player == "Christopher Smith"
	quietly replace Player = "Jarrod Clements" if Player == "Chunky Clements"
	quietly replace Player = "Clark Phillips III" if Player == "Clark Phillips"
	quietly replace Player = "Clay Matthews Jr." if Player == "Clay Matthews"
	quietly replace Player = "Decobie Durant" if Player == "Cobie Durant"
	quietly replace Player = "Cory Trice Jr." if Player == "Cory Trice"
	quietly replace Player = "Crevon LeBlanc" if Player == "Cre'von LeBlanc"
	quietly replace Player = "D'ante Smith" if Player == "D'Ante Smith"
	quietly replace Player = "Domonique Johnson" if Player == "D.J. Johnson"
	quietly replace Player = "DJ Montgomery" if Player == "D.J. Montgomery"
	quietly replace Player = "D.J. Ivey" if Player == "DJ Ivey"
	quietly replace Player = "D.J. Johnson" if Player == "DJ Johnson"
	quietly replace Player = "D.J. Turner" if Player == "DJ Turner"
	quietly replace Player = "Da'shawn Hand" if Player == "Da'Shawn Hand"
	quietly replace Player = "Davonte Lambert" if Player == "DaVonte Lambert"
	quietly replace Player = "Daesean Hamilton" if Player == "DaeSean Hamilton"
	quietly replace Player = "Dan Batten" if Player == "Danny Batten"
	quietly replace Player = "Dan Vitale" if Player == "Danny Vitale"
	quietly replace Player = "D.J. Ware" if Player == "Danny Ware"
	quietly replace Player = "Dante Fowler Jr." if Player == "Dante Fowler"
	quietly replace Player = "Darnell Savage" if Player == "Darnell Savage Jr."
	quietly replace Player = "Darrell Baker Jr." if Player == "Darrell Baker"
	quietly replace Player = "Darrell Luter Jr." if Player == "Darrell Luter"
	quietly replace Player = "David Rivers III" if Player == "David Rivers"
	quietly replace Player = "Scoota Harris" if Player == "De'Jon Harris"
	quietly replace Player = "DeVante Bausby" if Player == "De'Vante Bausby"
	quietly replace Player = "Devante Harris" if Player == "De'Vante Harris"
	quietly replace Player = "Devon Achane" if Player == "De'Von Achane"
	quietly replace Player = "Deandre Carter" if Player == "DeAndre Carter"
	quietly replace Player = "DeAndre Elliot" if Player == "DeAndre Elliott"
	quietly replace Player = "Deangelo Tyson" if Player == "DeAngelo Tyson"
	quietly replace Player = "Dee Alford" if Player == "DeAundre Alford"
	quietly replace Player = "Dejon Gomes" if Player == "DeJon Gomes"
	quietly replace Player = "Demarco Sampson" if Player == "DeMarco Sampson"
	quietly replace Player = "De'Michael Harris" if Player == "DeMichael Harris"
	quietly replace Player = "Deshawn Shead" if Player == "DeShawn Shead"
	quietly replace Player = "Deshon Elliott" if Player == "DeShon Elliott"
	quietly replace Player = "DeAndre Coleman" if Player == "Deandre Coleman"
	quietly replace Player = "Deatrich Wise" if Player == "Deatrich Wise Jr."
	quietly replace Player = "Taitusi Lutui" if Player == "Deuce Lutui"
	quietly replace Player = "Devin Bush" if Player == "Devin Bush Jr."
	quietly replace Player = "Dominque Alexander" if Player == "Dominique Alexander"
	quietly replace Player = "Donte Stallworth" if Player == "Donte' Stallworth"
	quietly replace Player = "Dorance Armstrong" if Player == "Dorance Armstrong Jr."
	quietly replace Player = "Douglas Hogue" if Player == "Doug Hogue"
	quietly replace Player = "E.J. Manuel" if Player == "EJ Manuel"
	quietly replace Player = "Earnest Brown" if Player == "Earnest Brown IV"
	quietly replace Player = "Eddy Pineiro" if Player == "Eddy Piñeiro"
	quietly replace Player = "Evan Smith" if Player == "Evan Dietrich-Smith"
	quietly replace Player = "Fitz Toussaint" if Player == "Fitzgerald Toussaint"
	quietly replace Player = "Foley Fatukasi" if Player == "Folorunso Fatukasi"
	quietly replace Player = "Gardner Minshew" if Player == "Gardner Minshew II"
	quietly replace Player = "Garret Hartley" if Player == "Garrett Hartley"
	quietly replace Player = "Gary Jennings" if Player == "Gary Jennings Jr"
	quietly replace Player = "Geno Grissom" if Player == "Geneo Grissom"
	quietly replace Player = "George Karlaftis" if Player == "George Karlaftis III"
	quietly replace Player = "Grant DuBose" if Player == "Grant Dubose"
	quietly replace Player = "Greg Newsome" if Player == "Greg Newsome II"
	quietly replace Player = "Greg Gatson" if Player == "Gregory Gatson"
	quietly replace Player = "Greg Rousseau" if Player == "Gregory Rousseau"
	quietly replace Player = "HaHa Clinton-Dix" if Player == "Ha Ha Clinton-Dix"
	quietly replace Player = "Hamilcar Rashed" if Player == "Hamilcar Rashed Jr."
	quietly replace Player = "Hardy Nickerson Jr." if Player == "Hardy Nickerson"
	quietly replace Player = "Henry Ruggs" if Player == "Henry Ruggs III"
	quietly replace Player = "Irv Smith" if Player == "Irv Smith Jr."
	quietly replace Player = "Issac Redman" if Player == "Isaac Redman"
	quietly replace Player = "Joe Unga" if Player == "J.J. Unga"
	quietly replace Player = "JK Dobbins" if Player == "J.K. Dobbins"
	quietly replace Player = "J.J. Arcega-Whiteside" if Player == "JJ Arcega-Whiteside"
	quietly replace Player = "J.J. Jones" if Player == "JJ Jones"
	quietly replace Player = "J.J. Nelson" if Player == "JJ Nelson"
	quietly replace Player = "J'Marcus Bradley" if Player == "Ja'Marcus Bradley"
	quietly replace Player = "Ja'whaun Bentley" if Player == "Ja'Whaun Bentley"
	quietly replace Player = "Janoris Jenkins" if Player == "Jackrabbit Jenkins"
	quietly replace Player = "Jake Martin" if Player == "Jacob Martin"
	quietly replace Player = "Jacob Byrne" if Player == "Jake Byrne"
	quietly replace Player = "Jamal Davis" if Player == "Jamal Davis II"
	quietly replace Player = "JaMycal Hasty" if Player == "Jamycal Hasty"
	quietly replace Player = "Jarvis Brownlee Jr." if Player == "Jarvis Brownlee"
	quietly replace Player = "Jason Taylor II" if Player == "Jason Taylor" & Team == "Los Angeles Rams"
	quietly replace Player = "Javelin Guidry Jr." if Player == "Javelin Guidry"
	quietly replace Player = "Jayson Dimanche" if Player == "Jayson DiManche"
	quietly replace Player = "Jedrick Wills" if Player == "Jedrick Wills Jr."
	quietly replace Player = "Jeffrey Gunter" if Player == "Jeff Gunter"
	quietly replace Player = "Johnny Newton" if Player == "Jer'Zhan Newton"
	quietly replace Player = "Jermaine Carter" if Player == "Jermaine Carter Jr."
	quietly replace Player = "Jermaine Johnson" if Player == "Jermaine Johnson II"
	quietly replace Player = "Jerrick Reed II" if Player == "Jerrick Reed"
	quietly replace Player = "JoLonn Dunbar" if Player == "Jo-Lonn Dunbar"
	quietly replace Player = "Jojo Domann" if Player == "JoJo Domann"
	quietly replace Player = "Joseph Anderson" if Player == "Joe Anderson"
	quietly replace Player = "Joe Milton III" if Player == "Joe Milton"
	quietly replace Player = "Joseph Morgan" if Player == "Joe Morgan"
	quietly replace Player = "Joe Tryon" if Player == "Joe Tryon-Shoyinka"
	quietly replace Player = "Josh Crockett" if Player == "John Crockett"
	quietly replace Player = "John Shenker" if Player == "John Samuel Shenker"
	quietly replace Player = "John Cyprien" if Player == "Johnathan Cyprien"
	quietly replace Player = "Jon Gaines II" if Player == "Jon Gaines"
	quietly replace Player = "Jonathan Hilliman" if Player == "Jon Hilliman"
	quietly replace Player = "Jon Runyan" if Player == "Jon Runyan Jr."
	quietly replace Player = "Jon Bostic" if Player == "Jonathan Bostic"
	quietly replace Player = "Johnathan Grimes" if Player == "Jonathan Grimes"
	quietly replace Player = "Joe Jones" if Player == "Joseph Jones"
	quietly replace Player = "Joshua Cribbs" if Player == "Josh Cribbs"
	quietly replace Player = "Joshua Hines-Allen" if Player == "Josh Hines-Allen"
	quietly replace Player = "Joshua Onujiogu" if Player == "Josh Onujiogu"
	quietly replace Player = "Joshua Thomas" if Player == "Josh Thomas" & (Team == "Carolina Panthers" | Team == "Seattle Seahawks" | Team == "New York Jets" | Team == "Detroit Lions" | Team == "Indianapolis Colts")
	quietly replace Player = "Joshua Uche" if Player == "Josh Uche"
	quietly replace Player = "Josh Kelley" if Player == "Joshua Kelley"
	quietly replace Player = "JuJu Hughes" if Player == "Juju Hughes"
	quietly replace Player = "Julie'n Davenport" if Player == "Julién Davenport"
	quietly replace Player = "K.C. McDermott" if Player == "KC McDermott"
	quietly replace Player = "K.J. Hamler" if Player == "KJ Hamler"
	quietly replace Player = "Kavontae Turpin" if Player == "KaVontae Turpin"
	quietly replace Player = "Reginald McKenzie" if Player == "Kahlil McKenzie"
	quietly replace Player = "Kam Kelly" if Player == "Kameron Kelly"
	quietly replace Player = "Keesean Johnson" if Player == "KeeSean Johnson"
	quietly replace Player = "Kennan Lambert" if Player == "Keenan Lambert"
	quietly replace Player = "Keivarae Russell" if Player == "KeiVarae Russell"
	quietly replace Player = "Kenneth Walker" if Player == "Kenneth Walker III"
	quietly replace Player = "Kenny Robinson" if Player == "Kenny Robinson Jr."
	quietly replace Player = "Kerrith Whyte" if Player == "Kerrith Whyte Jr"
	quietly replace Player = "Khadarel Hodge" if Player == "KhaDarel Hodge"
	quietly replace Player = "Kwamie Lassiter" if Player == "Kwamie Lassiter II"
	quietly replace Player = "Laron Byrd" if Player == "LaRon Byrd"
	quietly replace Player = "LaDarius Gunter" if Player == "Ladarius Gunter"
	quietly replace Player = "LaMarcus Joyner" if Player == "Lamarcus Joyner"
	quietly replace Player = "Delano Hill" if Player == "Lano Hill"
	quietly replace Player = "Larry Rountree III" if Player == "Larry Rountree"
	quietly replace Player = "Laviska Shenault" if Player == "Laviska Shenault Jr."
	quietly replace Player = "LeRon McClain" if Player == "Le'Ron McClain"
	quietly replace Player = "Leroy Hill" if Player == "LeRoy Hill"
	quietly replace Player = "Levante Bellamy" if Player == "LeVante Bellamy"
	quietly replace Player = "Leon McQuay III" if Player == "Leon McQuay"
	quietly replace Player = "Lil'jordan Humphrey" if Player == "Lil'Jordan Humphrey"
	quietly replace Player = "Lloyd Cushenberry" if Player == "Lloyd Cushenberry III"
	quietly replace Player = "Lonnie Johnson" if Player == "Lonnie Johnson Jr."
	quietly replace Player = "Louis Young" if Player == "Lou Young"
	quietly replace Player = "Louchiez Purifoy" if Player == "Loucheiz Purifoy"
	quietly replace Player = "Dontavian Jackson" if Player == "Lucky Jackson"
	quietly replace Player = "Lynn Bowden" if Player == "Lynn Bowden Jr."
	quietly replace Player = "Maake Kemoeatu" if Player == "Ma'ake Kemoeatu"
	quietly replace Player = "Malcolm Rodríguez" if Player == "Malcolm Rodriguez"
	quietly replace Player = "Marshawn Lloyd" if Player == "MarShawn Lloyd"
	quietly replace Player = "Marion Barber" if Player == "Marion Barber III"
	quietly replace Player = "Mark Fields" if Player == "Mark Fields II"
	quietly replace Player = "Marvell Tell" if Player == "Marvell Tell III"
	quietly replace Player = "Matt Bosher" if Player == "Matthew Bosher"
	quietly replace Player = "Matt Dayes" if Player == "Matthew Dayes"
	quietly replace Player = "Matt Jackson" if Player == "Matthew Jackson"
	quietly replace Player = "Matt McCrane" if Player == "Matthew McCrane"
	quietly replace Player = "Maurice Hurst" if Player == "Maurice Hurst Jr."
	quietly replace Player = "Mike Hoecht" if Player == "Michael Hoecht"
	quietly replace Player = "Mike Onwenu" if Player == "Michael Onwenu"
	quietly replace Player = "Michael Penix Jr." if Player == "Michael Penix"
	quietly replace Player = "Mike Woods" if Player == "Michael Woods II"
	quietly replace Player = "Michael Ford" if Player == "Mike Ford"
	quietly replace Player = "Michael Liedtke" if Player == "Mike Liedtke"
	quietly replace Player = "Michael Morgan" if Player == "Mike Morgan"
	quietly replace Player = "Michael Neal" if Player == "Mike Neal"
	quietly replace Player = "Nail Diggs" if Player == "Na'il Diggs"
	quietly replace Player = "Navorro Bowman" if Player == "NaVorro Bowman"
	quietly replace Player = "Nathan Bussey" if Player == "Nate Bussey"
	quietly replace Player = "Nathan Jones" if Player == "Nate Jones"
	quietly replace Player = "Nate Gerry" if Player == "Nathan Gerry"
	quietly replace Player = "Chinedum Ndukwe" if Player == "Nedu Ndukwe"
	quietly replace Player = "Neil Farrell Jr." if Player == "Neil Farrell"
	quietly replace Player = "Nick Deluca" if Player == "Nick DeLuca"
	quietly replace Player = "Nick Westbrook" if Player == "Nick Westbrook-Ikhine"
	quietly replace Player = "Nyheim Miller-Hines" if Player == "Nyheim Hines"
	quietly replace Player = "Olu Fashanu" if Player == "Olumuyiwa Fashanu"
	quietly replace Player = "Olu Oluwatimi" if Player == "Olusegun Oluwatimi"
	quietly replace Player = "Phillip Walker" if Player == "P.J. Walker"
	quietly replace Player = "P.J. Mustipher" if Player == "PJ Mustipher"
	quietly replace Player = "Patrick Angerer" if Player == "Pat Angerer"
	quietly replace Player = "Patrick Jones" if Player == "Patrick Jones II"
	quietly replace Player = "Lazarius Levingston" if Player == "Pep Levingston"
	quietly replace Player = "Phillip Loadholt" if Player == "Phil Loadholt"
	quietly replace Player = "Jartavius Martin" if Player == "Quan Martin"
	quietly replace Player = "Raymond Johnson III" if Player == "Raymond Johnson"
	quietly replace Player = "Reggie Robinson" if Player == "Reggie Robinson II"
	quietly replace Player = "Richard LeCount" if Player == "Richard LeCounte"
	quietly replace Player = "Richmond Mcgee" if Player == "Richmond McGee"
	quietly replace Player = "Ricky Jean Francois" if Player == "Ricky Jean-Francois"
	quietly replace Player = "Tariq Woolen" if Player == "Riq Woolen"
	quietly replace Player = "Robert Housler" if Player == "Rob Housler"
	quietly replace Player = "Robert McCray" if Player == "Rob McCray"
	quietly replace Player = "Robbie Anderson" if Player == "Robbie Chosen"
	quietly replace Player = "Robert Beal Jr." if Player == "Robert Beal"
	quietly replace Player = "Rob Kelley" if Player == "Robert Kelley"
	quietly replace Player = "Robert Tonyan Jr." if Player == "Robert Tonyan"
	quietly replace Player = "Rob Windsor" if Player == "Robert Windsor"
	quietly replace Player = "Rashad Carmichael" if Player == "Roc Carmichael"
	quietly replace Player = "Roderick Issac" if Player == "Rod Issac"
	quietly replace Player = "Rodney Thomas" if Player == "Rodney Thomas II"
	quietly replace Player = "Ron Leary" if Player == "Ronald Leary"
	quietly replace Player = "Johnathan Ford" if Player == "Rudy Ford"
	quietly replace Player = "SaRodorick Thompson Jr." if Player == "SaRodorick Thompson"
	quietly replace Player = "Sam Eguavoen" if Player == "Samuel Eguavoen"
	quietly replace Player = "Ahmad Gardner" if Player == "Sauce Gardner"
	quietly replace Player = "Sav Rocca" if Player == "Saverio Rocca"
	quietly replace Player = "Scooby Wright" if Player == "Scooby Wright III"
	quietly replace Player = "Scotty Miller" if Player == "Scott Miller"
	quietly replace Player = "Sean Bunting" if Player == "Sean Murphy-Bunting"
	quietly replace Player = "Sebastian Joseph" if Player == "Sebastian Joseph-Day"
	quietly replace Player = "Deion Calhoun" if Player == "Shaq Calhoun"
	quietly replace Player = "Shaq Quarterman" if Player == "Shaquille Quarterman"
	quietly replace Player = "Shaun-Dion Hamilton" if Player == "Shaun Dion Hamilton"
	quietly replace Player = "Stanley Morgan" if Player == "Stanley Morgan Jr."
	quietly replace Player = "Starling Thomas V" if Player == "Starling Thomas"
	quietly replace Player = "Steven Hauschka" if Player == "Stephen Hauschka"
	quietly replace Player = "Steve Schilling" if Player == "Stephen Schilling"
	quietly replace Player = "Steve Smith" if Player == "Steve Smith Sr."
	quietly replace Player = "Steven Sims Jr." if Player == "Steven Sims"
	quietly replace Player = "Iosua Opeta" if Player == "Sua Opeta"
	quietly replace Player = "Travis Carrie" if Player == "T.J. Carrie"
	quietly replace Player = "TJ Jones" if Player == "T.J. Jones"
	quietly replace Player = "TK McLendon Jr." if Player == "TK McLendon"
	quietly replace Player = "Taniela Tupou" if Player == "Tani Tupou"
	quietly replace Player = "Cornellius Carradine" if Player == "Tank Carradine"
	quietly replace Player = "Devonta Glover-Wright" if Player == "Tay Glover-Wright"
	quietly replace Player = "Jalen Tabor" if Player == "Teez Tabor"
	quietly replace Player = "Terrace Marshall" if Player == "Terrace Marshall Jr."
	quietly replace Player = "Bopete Keyes" if Player == "Thakarius Keyes"
	quietly replace Player = "Thayer Munford Jr." if Player == "Thayer Munford"
	quietly replace Player = "Thomas Graham Jr." if Player == "Thomas Graham"
	quietly replace Player = "Timothy Horne" if Player == "Timmy Horne"
	quietly replace Player = "Tre Hawkins III" if Player == "Tre Hawkins"
	quietly replace Player = "Tre' Sullivan" if Player == "Tre Sullivan"
	quietly replace Player = "Tre McKitty" if Player == "Tre' McKitty"
	quietly replace Player = "Tre'quan Smith" if Player == "Tre'Quan Smith"
	quietly replace Player = "Tre Tomlinson" if Player == "Tre'Vius Tomlinson"
	quietly replace Player = "Tre'Von Johnson" if Player == "Tre'von Johnson"
	quietly replace Player = "Trevon Moehrig" if Player == "Tre'von Moehrig"
	quietly replace Player = "Trenton Brown" if Player == "Trent Brown"
	quietly replace Player = "Trenton Robinson" if Player == "Trent Robinson"
	quietly replace Player = "TuTu Atwell" if Player == "Tutu Atwell"
	quietly replace Player = "Tyreek Maddox-William" if Player == "Tyreek Maddox-Williams"
	quietly replace Player = "Ty Davis-Price" if Player == "Tyrion Davis-Price"
	quietly replace Player = "Tyrone Tracy" if Player == "Tyrone Tracy Jr."
	quietly replace Player = "Velus Jones" if Player == "Velus Jones Jr."
	quietly replace Player = "Vernon Hargreaves" if Player == "Vernon Hargreaves III"
	quietly replace Player = "Vladimir Ducasse" if Player == "Vlad Ducasse"
	quietly replace Player = "Walter Powell" if Player == "Walt Powell"
	quietly replace Player = "Wan'dale Robinson" if Player == "Wan'Dale Robinson"
	quietly replace Player = "Warren McClendon Jr." if Player == "Warren McClendon"
	quietly replace Player = "Wendell Williams" if Player == "Wendall Williams"
	quietly replace Player = "William Beatty" if Player == "Will Beatty"
	quietly replace Player = "Will Bradley-King" if Player == "William Bradley-King"
	quietly replace Player = "Will Compton" if Player == "William Compton"
	quietly replace Player = "William Jackson" if Player == "William Jackson III"
	quietly replace Player = "Will Sherman" if Player == "William Sherman"
	quietly replace Player = "Willie Harvey Jr." if Player == "Willie Harvey"
	quietly replace Player = "Yannik Cudjoe-Virgil" if Player == "Yannick Cudjoe-Virgil"
	quietly replace Player = "Zac Diles" if Player == "Zach Diles"
	quietly replace Player = "Zach Carter" if Player == "Zachary Carter"
	quietly replace Player = "Zach Thomas" if Player == "Zachary Thomas"
	quietly replace Player = "Zachary Johnson" if Player == "Zack Johnson"
	quietly replace Player = "Ezekiel Turner" if Player == "Zeke Turner"
}
drop Flag

quietly recol, full
save "C:/Users/Owner/OneDrive/Documents/Georgetown University/Thesis Writer/Research/QB Worth/Season Analysis/Data 6 Season AV Clean.dta", replace